### ISSUE TITLE
Parser is locked away in /internal/

### ISSUE THREAD

**Issue by shelbyramsey** [graph-gophers/graphql-go#116]
Recently for a project we've had a need to parse & store gql queries in a structured manner that can easily be queried in a database. After quite minimal effort I was able to accomplish this thanks to the well done parser in the /internal/ directory.

That being said the code can not be used outside of the repo. I can appreciate not wanting to support backwards compatibility on the API but it was not clear as I was digging through it whether this was a concern or not. I'd be happy to do the work to deal with the migration if the maintainers are open to it. 

Thanks again for the great contribution to the community!

**Comment by Vektah** [comment]
I would love to see `internal/parser`, `internal/validation` and `internal/schema` pulled into stand alone library. 

They would be very useful for building all kinds of graphql cli tools and proxies.

**Comment by emwalker** [comment]
It's a pity.  I was quite enthusiastic about this library, until I realized I would need to get ahold of a parsed document to do what I needed, and then I discovered that the code for this is in `internal`.  This friendly worded issue was filed in October of last year, and no response.

**Comment by vvakame** [comment]
Hi, I'm very interested in this topic.
I want to know what members are thinking 🌹 

http://facebook.github.io/graphql/June2018/ is out.
[vgo](https://github.com/golang/go/wiki/vgo#current-state) supports [semver](https://semver.org/), we can also specify a breaking change.

**Comment by bsr203** [comment]
I use couple of libs written by @vvakame and his contribution to graphql-go would be great!! Also agree with versioning this lib as per the graphql spec version.

**Comment by emwalker** [comment]
For anyone encountering this, see gqlgen, which is a [hard fork](https://github.com/99designs/gqlgen/issues/35).

**Comment by pavelnikolov** [comment]
#437 437 solves that
