### ISSUE TITLE
[HELP] How to query over HTTP?

### ISSUE THREAD

**Issue by sbe88** [graph-gophers/graphql-go#131]
Hi,

What would the following line become to be able to query from a client over HTTP and get the response back? I've been searching around for quite a long time, sorry for asking this here...

```graphql
// in graphql-go/example/starwars/server/server.go
http.Handle("/gql", &relay.Handler{Schema: schema})
```

**Comment by lpalmes** [comment]
Hey @sbe88, that line setups the route to handle requests in your the server, what you have to do is send a POST request to the server with the query in the body in json format.

```
{
  "query": "{ hello }",
  "operationName": "",
  "variables": {}
}
```

I've made a quick repo as an [introduction to graphql-go](https://github.com/lpalmes/graphql-go-introduction), but i've stopped writing because of the new resolvers api.

Hope it helps!

**Comment by sbe88** [comment]
Hey @lpalmes , thanks a lot for your response, I've read your documentation. However, I'm sincerely stuck.

Just reproducing the steps that seemed obvious at first did not get me anywhere. So I started faking some data and stuff to test it out. 

The farthest I could get is this sexy message in the browser :open_mouth: 

RelayResponseNormalizer(): Expected a typename for record `{ "id": "1000", "name": "Luke Skywalker", "appearsIn": [ "NEWHOPE", "EMPIRE", "JEDI" ] }`.

**And I'm actually totally faking it. I'd like to use starwars.go instead of hardcoding that stuff.** If you got a minute for checking this out, that would be much appreciated.

**Client on port 3000**, has endpoint http://localhost:8080/graphql :

```jsx
import React from 'react'
import { QueryRenderer, graphql } from 'react-relay'

const JediQuery = graphql`
         query JediQuery{
           character(id: 1000) {
             id
             name
           }
         }
     `

class Jedi extends React.Component {
  render() {
    console.log('JEDI', this.props)
    return (
      <div>
        <QueryRenderer
          environment={this.props.environment}
          query={JediQuery}
          operationName="query"
          variables=""
          render={({ error, props }) => {
            if (error) {
              return <div>{error.message}</div>;
            } else if (props) {
              return <div>{props.character.name} is great!</div>;
            }
            return <div>Loading</div>;
          }}
        />
      </div>
    )
  }
}
export default Jedi
```
**server.go on port 8080**

```go
package main

import (
	"encoding/json"
	"log"
	"net/http"

	"github.com/neelance/graphql-go"
	"github.com/neelance/graphql-go/example/starwars"
	"github.com/neelance/graphql-go/relay"
)

var schema *graphql.Schema

func init() {
	schema = graphql.MustParseSchema(starwars.Schema, &starwars.Resolver{})
}

type Response struct {
	Data Data `json:"data"`
}

type Data struct {
	Character Character `json:"character"`
}

type Character struct {
	Id        string   `json:"id"`
	Name      string   `json:"name"`
	AppearsIn []string `json:"appearsIn"`
}

func main() {

	port := ":8080"
	log.Printf(`GraphQL server starting up on http://localhost%v`, port)

	http.Handle("/query", &relay.Handler{Schema: schema})

	http.HandleFunc("/graphql", func(w http.ResponseWriter, r *http.Request) {

		data := Response{
			Data: Data{
				Character: Character{
					Id:        "1000",
					Name:      "Luke Skywalker",
					AppearsIn: []string{"NEWHOPE", "EMPIRE", "JEDI"},
				},
			},
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusCreated)
		json.NewEncoder(w).Encode(data)
	})

	log.Fatal(http.ListenAndServe(port, nil))
}
```

**Comment by sbe88** [comment]
It was just a header problem in the client...

`http.HandleFunc("/graphql", &relay.Handler{Schema: schema})` worked in the end.

**Comment by lpalmes** [comment]
Hey @sbe88, i've never knew you responded, i've must missed the notification, i'm sorry about that. Glad that you made it work out. Did you have a cors problem? So other people find the solution if they ever come by a problem like that

**Comment by sbe88** [comment]
Hi @lpalmes, thanks, no worries. I have commented out the headers in my client for now and this resolved the issue. I haven't had the time to dig deeper on this yet, if you got a thought, please feel free to share.

```node
return fetch(process.env.RELAY_ENDPOINT, {
    method: 'POST',
    // headers: {
    //   'Accept': 'application/json',
    //   'Content-Type': 'application/json'
    // },
    body: JSON.stringify({
      query: operation.text,
      variables
    })
  }).then(response => response.json())
```

**Comment by tonyghita** [comment]
This seems resolved; feel free to open if not.
