### ISSUE TITLE
How do you maintain large GraphQL schema (discussion)

### ISSUE THREAD

**Issue by darh** [graph-gophers/graphql-go#160]
Any suggestions ideas or examples on how to maintain large GraphQL schema? At the moment I have 700 lines with 26 types, 6 unions, 4 interfaces and 9 enums stacked in one long string. Final numbers will be 2-3x higher.

I'm splitting resolvers in multiple query and mutation .go files and initial idea was to split the schema string as well. But that cripples error reporting's line information.

**Comment by tonyghita** [comment]
Hey, check out the example I have in [github.com/tonyghita/graphql-go-example](https://github.com/tonyghita/graphql-go-example/tree/7e2037a97840f4b7579dd32d5a2ded7375c6b2fc/schema).

The schema directory is traversed and all `*.graphql` files are concatenated together into a string at build time.

**Comment by DenisNeustroev** [comment]
At build time it's concatenated into one .graphql file in upper directory, after that this file is given to the program.
<img width="159" alt="image" src="https://user-images.githubusercontent.com/4533828/36017168-96c800d6-0d87-11e8-990c-a9b0c83d19ab.png">

**Comment by tonyghita** [comment]
I wonder if this is functionality that should be built in to the library 🤔

**Comment by nikkon226** [comment]
I have done what @DenisNeustroev has suggested (using the new strings.Builder type from 1.10):

    var Schema string

    func init() {
      var s strings.Builder
      files, err := filepath.Glob("gql/schema/*.gql")
      if err != nil {
        panic(err)
      }
      for _, f := range files {
        file, err := os.Open(f)
        if err != nil {
          panic(err)
        }
        defer file.Close()
        scanner := bufio.NewScanner(file)
        for scanner.Scan() {
          _, err = s.Write(scanner.Bytes())
          if err != nil {
            panic(err)
          }
          _, err = s.WriteString("\n")
          if err != nil {
            panic(err)
          }
        }
      }
      Schema = s.String()
    }

**Comment by dvic** [comment]
I can also recommend using https://github.com/gobuffalo/packr instead of go-bindata for this purpose.

**Comment by GhostRussia** [comment]
@dvic go-bindata is more lightweight, since it simply generates a file without dependencies. 
But in this case, you can write your utility code-based https://github.com/graph-gophers/graphql-go/issues/160#issuecomment-369762034, or even use bash to generate a schema file.
All we need is to merge the lines of files and assign them to one variable.

```go
package schemaPackageName

const schema = `
schema {
  query: Query
}
type Query {
...
}
`
```

simple bash script:
`schema.sh`
```bash
#!/bin/bash

PACKAGE="schema" # package name
FILE="schema.go" # output file
GRAPHQL="." # *.graphql files directory

echo "package $PACKAGE" > $FILE # set package name
echo "" >> $FILE # new line
echo "const schema = \`" >> $FILE # set const

find $GRAPHQL -name '*.graphql' | xargs -I{} sh -c "cat {}; echo ''" >> $FILE # load all graphql files in $GRAPHQL directory

echo "\`" >> $FILE
```

this script supports go generate:
`gen.go`
```go
//go:generate ./schema.sh
package schema
```

**Comment by tonyghita** [comment]
These are some good approaches to keeping GraphQL servers deployable as single binaries. We should note the general approach and one or two solutions in the README.

Closing this issue and creating an item to add relevant documentation in the [roadmap](https://github.com/graph-gophers/graphql-go/projects/1).
