### ISSUE TITLE
Did the repository owner just change?

### ISSUE THREAD

**Issue by nikkon226** [graph-gophers/graphql-go#172]
I swear that the owner was @neelance yesterday.... so what's going on with the change?

**Comment by neelance** [comment]
Yes, I transferred the repo to this new org and @tonyghita volunteered to become a maintainer (thanks!), since I am busy working on the WebAssembly support for the Go compiler.

**Comment by nikkon226** [comment]
Awesome, thank you very much for your work @neelance and thanks for taking over @tonyghita !
