### ISSUE TITLE
"Getting started" questions

### ISSUE THREAD

**Issue by mytototo** [graph-gophers/graphql-go#177]
Hi there,

I just started working with GraphQL in Go. I have read the API docs and some examples. Still, I'm stuck with some things.

Given the following schema, I have a few questions:

1. How is it possible to have both field and method names for a specific type ? `Name`, `Age` are both field and method. What is your workaround about this ?
2. Why the `Age` method works fine with pointer whereas the `Name` method does not ?
3. Is there a way to automatically return `Name` and `Age` from the `User` type without writing a method for each of them ?
4. How do you handle `*.graphql` files loading ? Having a single string is a bit annoying.
5. How do you handle depth limiting and other security guidelines ?

```go
package project

import (
	"context"
)

var Schema = `
	schema {
		query: Query
	}
	
	type Query {
		user(id: ID!): User
	}

	type User {
		name: String!
		age: Int
		isAdmin: Boolean!
	}
`

type Resolver struct{}

type User struct {
	Name string
	Age int32
}

func (r *Resolver) User(ctx context.Context, args struct{ ID int32 }) (*User, error) {
	return &User{
		Name: "foo",
		Age: 25,
	}, nil
}

func (u *User) Name(ctx context.Context) string {
	return u.Name
}

func (u *User) Age(ctx context.Context) *int32 {
	return &u.Age
}

func (u *User) IsAdmin(ctx context.Context) bool {
	return false
}
```

Thank you for your time and support.

**Comment by GhostRussia** [comment]
1) Add new struct "UserResolver" with "User"
```go
type User struct {
	Name string
	Age int32
}

type UserResolver struct {
	User *User
}
...
func (u *UserResolver) Name(ctx context.Context) string {
	return u.User.Name
}
...
```

2) http://graphql.org/learn/schema/

```name: String!``` (Non-Null string)

```go
var Schema = `
...
	type User {
		name: String!
		...
	}
`
...
func (u *User) Name(ctx context.Context) string {
	...
}
```

```name: String``` (can be Null)
```go
var Schema = `
...
	type User {
		name: String
		...
	}
`
...
func (u *User) Name(ctx context.Context) *string {
	...
}
```
3) No, but you can use generators

**Comment by GhostRussia** [comment]
3. Using the self-written methods allows you to make the necessary calculations only when you ask for the required field.

ResolveImage
```go
...
func (r *ImageResolver) Votes(ctx context.Context) (*ImageVoteResolver, error) {
	return ResolveImageVote(ctx, r.Image.ID) // Request to the database only if we request the field "Votes"
}
...
```

ResolveImageVote
```go
...
func (r *ImageVoteResolver) Up() int32 {
	return int32(r.ImageVote.Plus)
}

func (r *ImageVoteResolver) Down() int32 {
	return int32(r.ImageVote.Minus)
}

func (r *ImageVoteResolver) Favorite() int32 {
	return int32(r.ImageVote.Plus)
}

func (r *ImageVoteResolver) Count() int32 {
	return int32(r.ImageVote.Plus + r.ImageVote.Minus) // calculations
}

func (r *ImageVoteResolver) Score() int32 {
	return int32(r.ImageVote.Plus - r.ImageVote.Minus) // calculations
}
...
```

**Comment by mytototo** [comment]
Thank you for your help @GhostRussia. I just tested your solutions and it works as expected.

Regarding the question 4, I found related issues such as #160.
