### ISSUE TITLE
Is there a plan for a code generator?

### ISSUE THREAD

**Issue by dengliu** [graph-gophers/graphql-go#183]
Hi @tonyghita 

Is there a plan for a code generator based on this library?
Thank you.

**Comment by tonyghita** [comment]
Yes, although I don't have time to provide an open source solution at the moment. It's possible to build one fairly quickly using the `introspection` package here and Go's excellent `text/template` standard library.

I encourage you to check out https://github.com/vektah/gqlgen in the meantime, if you need something with codegen out of the box today.

**Comment by abihf** [comment]
Hi I'm trying to make code generator for it.
https://github.com/abihf/graphql-codegen

**Comment by salmana1** [comment]
hello,

There is also this if anyone interested: https://github.com/DealTap/graphql-gen-go

**Comment by sjakati98** [comment]
Any word on this @tonyghita? Or is it still advised to use gqlgen?

**Comment by tonyghita** [comment]
I don't have anything ready to publish and use, or the time to work on one to do so. A good code generation-based library I'd recommend is https://github.com/99designs/gqlgen.
