### ISSUE TITLE
Support for string literals as description

### ISSUE THREAD

**Issue by SpaceHeroGuide** [graph-gophers/graphql-go#196]
As of version 0.12.3 the default style of describing a type or field is to add a string literal instead of a comment.
https://github.com/graphql/graphql-js/blob/master/src/utilities/extendSchema.js#L44

Using the schema
```graphql
"This is a description."
schema {
    query: Query
}
```
results in a crash.

**Comment by geertjanvdk** [comment]
A small concern, the GraphQL specification states that only [comments start with #](http://facebook.github.io/graphql/October2016/#sec-Comments). This will remain right? Because I see that "Support descriptions; deprecate comment functionality", and deprecation would violate that, or I miss understood the roadmap entry?

**Comment by vektah** [comment]
Yep, comments are comments, as far as the spec is concerned they should be treated as whitespace.

Descriptions are quoted strings that act like a little like comments but are added to the description field for the type they precede in the introspection api.

see also:
 - [Comments](https://github.com/facebook/graphql/blob/master/spec/Section%202%20--%20Language.md#comments)
 - [Descriptions](https://github.com/facebook/graphql/blob/master/spec/Section%203%20--%20Type%20System.md#descriptions)
 - [grammar](https://github.com/facebook/graphql/blob/master/spec/Appendix%20B%20--%20Grammar%20Summary.md)

**Comment by geertjanvdk** [comment]
OK, so we talk about the "draft" of the new specification. I hope that deprecation comes after the new spec is released, not while we still are using the ancient 20016 spec :)

**Comment by vektah** [comment]
The schema IDL only exists in the draft spec. I think it makes sense to keep up to date with it. The current "stable" is years behind and only specifies the query syntax afaik.
