### ISSUE TITLE
Example for how to use relay functionality

### ISSUE THREAD

**Issue by reem** [graph-gophers/graphql-go#197]
There appears to be minor support for relay, but for the life of me I cannot figure out where/how I am supposed to call the relay helper functions like `MarshalID` and `UnmarshalSpec`. A simple example that actually uses these functions would go a really long way to making this library easier to use when setting up a relay server.

**Comment by maxbeatty** [comment]
We're using the `relay` package and it's been really nice and lightweight. The [existing example](https://github.com/graph-gophers/graphql-go/blob/9ebf33af539ab8cb832c7107bc0a978ca8dbc0de/example/starwars/) is [using `relay.Handler` already](https://github.com/graph-gophers/graphql-go/blob/9ebf33af539ab8cb832c7107bc0a978ca8dbc0de/example/starwars/server/server.go#L23). You need to implement a `Node` interface and resolver which is almost identical to what [`character` and `characterResolver` are](https://github.com/graph-gophers/graphql-go/blob/9ebf33af539ab8cb832c7107bc0a978ca8dbc0de/example/starwars/starwars.go#L372-L382).

[Resolving the `ID` of a `Human`](https://github.com/graph-gophers/graphql-go/blob/9ebf33af539ab8cb832c7107bc0a978ca8dbc0de/example/starwars/starwars.go#L398-L400) or any other type should use `MarshalID` to satisfy [Relay's Object Identification](https://facebook.github.io/relay/docs/en/graphql-server-specification.html#object-identification)

```diff
func (r *humanResolver) ID() graphql.ID {
-	return r.h.ID
+       return relay.MarshalID("Human", r.h.ID)
}
```

Similarly when [resolving a `Human` by `ID`](https://github.com/graph-gophers/graphql-go/blob/9ebf33af539ab8cb832c7107bc0a978ca8dbc0de/example/starwars/starwars.go#L334-L339), you would use `UnmarshalSpec` to get the key for `humanData`:

```diff
- func (r *Resolver) Human(args struct{ ID graphql.ID }) *humanResolver {
+ func (r *Resolver) Human(args struct{ ID graphql.ID }) (*humanResolver, error) {
+        var humanID string
+        if err := relay.UnmarshalSpec(args.ID, &humanID); err != nil {
+		return nil, err
+	}

-	if h := humanData[args.ID]; h != nil {
+	if h := humanData[humanID]; h != nil {
-		return &humanResolver{h}
+		return &humanResolver{h}, nil
	}
-	return nil
+	return nil, nil
}
```

Hope this helps!

**Comment by reem** [comment]
Thank you very much this is very helpful!

**Comment by matiasanaya** [comment]
@reem is there anything outstanding stoping this issue from being resolved / closed?
