### ISSUE TITLE
graph.Time and storage in Postgres

### ISSUE THREAD

**Issue by smithaitufe** [graph-gophers/graphql-go#198]
Please it is really urgent for me to get this done.

What is the equivalent datatype in Postgres to store graphql.Time{ Time: time.Now()} ?

What is the best approach?

**Comment by darh** [comment]
I'm using `graphql.Time` on the query/mutation site and then pick out `.Time` field from it when I need it (e.g. `cmp.ExpiresAt = &input.ExpiresAt.Time` where `cmp.ExpiresAt` is `time.Time` and `input.ExpiresAt` is `graphql.Time`).

**Comment by smithaitufe** [comment]
So at the model strut, you have `time.Time` and the input fields in your mutation, you have graphql.Time. So before saving to DB, you simply do the conversion. Please can you send a sample?

**Comment by darh** [comment]
There's really no extra sample.

Use graphql.Time for "graphql input" models and time.Time for your "db models" and cast on mutation, before you push it to the db. BTW -- I'm using GORM to store data.

**Comment by smithaitufe** [comment]
Thanks. I am using sqlx. 

In my model I used graphql.Time.

Initially, I used time.Time. It was inserted but graphql couldn't render it when I queried it.

I will try your suggestion and get back to you

**Comment by darh** [comment]
Should make no difference (sqlx vs gorm) as value is serialized on the driver level. Just reassign to proper types and shove it into the db :)

**Comment by smithaitufe** [comment]
@darh Thanks. It is working fine now. I am closing this issue
