### ISSUE TITLE
Middleware support? For stats, logs, etc.

### ISSUE THREAD

**Issue by tejasmanohar** [graph-gophers/graphql-go#200]
Hey there! Does this library support "middleware"?

I'd like to output some generic logs + metrics from my GraphQL application. Some examples are errors that happen in a resolver, the time each resolver takes, how many times each resolver is called, etc. I'm used to using JSONRPC via gorilla/rpc and GRPC, which both have support for this. Here are some examples of what I mean
- http://www.gorillatoolkit.org/pkg/rpc#Server.RegisterBeforeFunc
- http://www.gorillatoolkit.org/pkg/rpc#Server.RegisterAfterFunc
- https://github.com/grpc-ecosystem/go-grpc-middleware

Even if it's not currently supported, does anyone else have a use case for this? Would the maintainers accept a PR for it?

**Comment by smithaitufe** [comment]
Hi, check the go-graphql-starter project listed as community example in the home page.

It has custom logging support using go-logging package.

I think it will give you a head way

**Comment by tejasmanohar** [comment]
@smithaitufe Maybe I'm missing something but you have to add logging to every resolver, right? Is there a generic way to just operate on "resolver names" in middleware? Example:

```
graphql.RegisterBeforeFunc(func(resolverName string) {
  log.Info("Before %s executed")
 // store start time somewhere
})

// and same thing after w/ end time
```

In addition, I feel this overuses `ctx.Value()` for something that could be done otherwise, introducing more potential runtime type errors 😞. What do you think?

**Comment by smithaitufe** [comment]
Nope. You add it to the route that handles your request. For example,
```
handlerWithContext := h.AppendContext(ctx, &h.Handler{Schema: parsedSchema, Loaders: loaders.NewLoaderCollection()})
http.Handle("/graphql", c.Handler(loggerHandler.Logging(handlerWithContext)))
http.Handle("/graphql/", c.Handler(loggerHandler.Logging(handlerWithContext)))
```
Then you can handle the logging in the loggerHandler.Logging which should return a http.Handler as well.


As for ctx.Value, it is up to you. If you wish to use a global DB, you can go ahead. In NodeJS, you can use a context or you simply import your database.

The same is applicable here.

**Comment by pavelnikolov** [comment]
The purpose of the library is to be minimalistic and not try to solve every problem of every user. I am closing this issue as stale.

**Comment by skolodyazhnyy** [comment]
@pavelnikolov middleware is a good way to keep library minimalistic, by adding middleware you can help users to extend core without adding features to it. Without middleware on the other hand you lock in users in what is implemented. 

For example, I'm looking into adding request level caching to individual resolvers (eg. user requested comment with ID 5 in two different parts of the tree within same request), right now this does not seem to be possible without changing core. You can not get it done without changing core, on the other hand middleware may allow such features to be implemented without changing core, which means core would be smaller (ie. minimalistic) while additional features still will be possible.

**Comment by pavelnikolov** [comment]
We are on the same page re middleware. I have been thinking about that. The problem with this library, though, is that if we want to implement what you suggest we might need to change the public API and probably introduce versioning + a new major version. There are many users and ideally I want to avoid breaking changes. The way resolvers are implemented right now makes it difficult to add middleware. (not impossible). I will think about that.
