### ISSUE TITLE
@deprecated directive on `input`

### ISSUE THREAD

**Issue by rogchap** [graph-gophers/graphql-go#204]
Since https://github.com/graph-gophers/graphql-go/commit/498fe3961c3058c45f5ad90b1212a48adfbba266 we can add `@deprecated` to types like so:

```graphql
type User {
  name: String!
  age: int @deprecated(reason: "Use `dob` instead")
  dob: Date!
}
```

However the `@deprecated` directive throws an error on `input`:

```graphql
input UserInput {
  name: String!
  age: int! = 0 @deprecated(reason: "Use `dob` instead")
  dob: Date!
}
```
```
panic: graphql: syntax error: unexpected "@", expecting Ident
```

**Comment by rogchap** [comment]
Also found that it's not supported on Field Args either, eg:
```graphql
type User {
  properties(
    limit: int = 20 @deprecated(reason: "limit is no longer supported, always returns all")
  ): [Property!]!
}
```
```
panic: graphql: syntax error: unexpected "@", expecting Ident
```

**Comment by vektah** [comment]
I've started work in a new parser that should support all of these and a bunch of other new features like schema extensions. It's up to Tony if that lands here, but feel free to have a look.

https://github.com/vektah/gqlparser

**Comment by rogchap** [comment]
Looks interesting @vektah Thanks for sharing.
`gqlgen` looks good too; just wondering why you created a new project, rather than contributing to this one? Would be nice to have a "de facto" GraphQL Server for Golang... much like Apollo is for Javascript.

**Comment by vektah** [comment]
At the time I started writing [gqlgen](http://github.com/vektah/gqlgen) this package was unmaintained, and I wanted to take it in a very different direction (the whole execution phase & json marshalling is generated out as go code). I can't realistically expect anyone to merge a 5k+ line PR to the core request executor.

I still think a heap of work can be shared, bringing the whole go graphql ecosystem forward, like getting a robust parser & validator out independent of the server.

**Comment by smitt04** [comment]
This is working its way into the spec https://github.com/facebook/graphql/pull/525
