### ISSUE TITLE
Support for async field resolution

### ISSUE THREAD

**Issue by racevedoo** [graph-gophers/graphql-go#208]
Hi all and thanks for this great project!

I was wondering if there are plans to add concurrent field resolution. I noticed that there is support for concurrecy when multiple queries are issued on the same request. Are there plans to add similar funcionality for fields?

Thanks!

**Comment by Frobozz390** [comment]
My experimental observation is that this is already in place; glancing at the code in execSelections and execSelectionSet there are certainly several points where goroutines are created that wind up resolving scalar fields.

My question is the inverse - is there a way to control concurrent resolution?  It seems to be enabled possibly depending on the signature of the resolve method?

Thanks!

**Comment by aaahrens** [comment]
Can this be closed?
