### ISSUE TITLE
New authentication package for graphql-go

### ISSUE THREAD

**Issue by astenmies** [graph-gophers/graphql-go#215]
Hi everyone,

I have been working on a small authentication package inspired by gologin. It provides Oauth2 google authentication for now and I plan to add more. 

The goal of this package was to not have a specific route to login, so the request is triggered through a regular mutation. The login handlers are bypassed if the request is not the "trigger" mutation.

Each step was split in different http.Handlers in order to get as much flexibility as possible.
Please feel free to have a look and advise or contribute. 

I'd be happy to transfer the ownership to graph-gophers if interested in order to encourage contributions.

https://github.com/astenmies/graphql-go-auth

**Comment by pavelnikolov** [comment]
This is way too specific implementation. I don't think it should be part of this library. Also, it doesn't feel very GraphQL-idiomatic to me.
IMHO, when this library supports extensions, it'd be possibe to add extension which allows declarative authorization/authentication.

**Comment by maxbeatty** [comment]
I very much like the current approach where I can bring my own router and auth solutions and fit graphql-go in as I see fit. 

Perhaps more robust example projects that include auth or GraphiQL (#221) could show how to tie all of these wants together 😸

**Comment by pavelnikolov** [comment]
Examples should be always welcomed in any project.

**Comment by pavelnikolov** [comment]
I am closing this issue as stale and not directly related to the core of the library.
@maxbeatty more robust examples are welcome in the community examples section of the README.md (I'm planning to move this out to its own markdown document).
