### ISSUE TITLE
Hope to use internal pkg

### ISSUE THREAD

**Issue by liubog2008** [graph-gophers/graphql-go#222]
1. Why parser is in internal pkg?

2. Is there any way to use gql parser directly?

3. Could I copy internal pkg into my own project?

4. Is there any plan to change it?

**Comment by liubog2008** [comment]
@neelance

**Comment by neelance** [comment]
The project has a BSD licence, you can do what it allows you to do. I myself have no intention to open up the parser package because it would contradict the project goal "minimal API".

**Comment by liubog2008** [comment]
Thanks @neelance
