### ISSUE TITLE
Cannot use library with go1.7

### ISSUE THREAD

**Issue by ss-limafriyadi** [graph-gophers/graphql-go#231]
Hello,

When I try to use this with go1.7 it returns the following error

```
# vendor/github.com/graph-gophers/graphql-go/internal/validation
vendor/github.com/graph-gophers/graphql-go/internal/validation/suggestion.go:25: undefined: sort.Slice
# vendor/github.com/graph-gophers/graphql-go/trace
vendor/github.com/graph-gophers/graphql-go/trace/validation_trace.go:7: syntax error: unexpected = in type declaration
```

I found that `sort.Slice` first released in go1.8 and `type =` syntax is introduced in go1.9.

Can we make this compatible with go1.7?

**Comment by pavelnikolov** [comment]
I guess that we definitely need to document the minimal required Go version! Thanks for reporting this.

**Comment by ss-limafriyadi** [comment]
Any plan to support go1.7? Or must we use minimum working version of go1.9?

**Comment by pavelnikolov** [comment]
I don't think we need to support old versions. However from a single glance this type aliasing doesn't seem to be necessary at all. We could just use the existing func, no? I have to dig deeper into this code.
