### ISSUE TITLE
Interface can't be used as nullable resolver

### ISSUE THREAD

**Issue by Veilyon** [graph-gophers/graphql-go#233]
Hello,

I'm currently trying to use a go-interface as nullable resolver.
The structure of my code is like this:
```graphql
type Foo {
   getBar(): Bar
}

type Bar {
   doBarThings(): Bool!
}
```

```go
type Foo struct {}

func (f *Foo) GetBar() Bar {
	if someCondition {
		return &SpecificBar{}
	} else {
		return nil
	}
}

type Bar interface {
   DoBarThings() bool
}

type SpecificBar struct {}

func (sb *SpecificBar) DoBarThings() bool {
   // ...
   return true
}
```
This whole thing works without any problems, as long as `Bar` is not `nil`,
in which case I get `graphql: panic occurred: reflect: Method on nil interface value`.

Replacing 
```go
GetBar() Bar
```
with
```go
GetBar() *SpecificBar
```
Would fix the problem, however, I do want to have the option to have specific implementations for the `Bar` type.

My guess would be that this is a (somehow) desired behaviour, since nil interface values are a thing.
However, I never casted my `nil` to `Bar`, which (to my knowledge) would be required for nil to be recognized as interface value.

I have also tried to pass the interface as a pointer, in the hopes that it would trigger the library to expect a nillable value (like it is required for nullable arrays):
```go
GetBar() *Bar
```
Which just leads to `*Bar does not resolve "Bar": missing method for field "doBarThings"`.

**Comment by pavelnikolov** [comment]
I'm not 100% sure I understand your example. Shouldn't you use [GraphQL interfaces](https://graphql.org/learn/schema/#interfaces) in the first place?

**Comment by Veilyon** [comment]
The primary use case I have is to decouple the resolvers implementation from it`s (go) definition.
I have my code spread across multiple packages:
```
- resolver/foos
- resolver/bars
```
I already reference a resolver defined in `bars` from a resolver defined in `foos`, e.g.
```go
package foos

import "bars"

type Foo struct { }

func (f *Foo) GetBar() *bar.Bar {
    return getBarFromSomewhere()
} 
```
This works without a problem, of course.
But now I want to add the ability to also go the other way - from `Bar` to `Foo`.
This would require a circular import (`foos` imports `bars`, `bars` imports `foos`), which is disallowed by Go.

My solution to that problem would be to implement the resolvers as interface, e.g.
package:
```
- resolvers/definitions
```
interface:
```go
type Bar interface {
    DoBarThings() bool
}
```
Which then allows me to use the `definitions` package instead of `bars` directly.
This works without any problem, as long as the returned value is not `nil` - which, sadly, is the case sometimes.

**Comment by pavelnikolov** [comment]
Are you using untyped nil? Can you try returning `(Bar)(nil)`? Alternatively, you can try this:
```
var a Bar
if condition {
        a = &SpecificBar{}
}
return a
```
I haven't tested any of the above, though...

**Comment by Veilyon** [comment]
Typed nil gives the same result as untyped nil (`graphql: panic occurred: reflect: Method on nil interface value`).

As far as I can say it isn't even directly caused by the library.
It does seem to be the `reflect` package, which parses even untyped nils to typed ones, if they are returned for an interface type.

Still, it would be nice if there would be some way to return a nil-value for interface resolvers.
