### ISSUE TITLE
cameCase for object fields

### ISSUE THREAD

**Issue by fuintis** [graph-gophers/graphql-go#247]
Hello to everyone:

I'm trying to develop a GraphQL server with this lib but when i send a query to the API the response have fields in snake_case. Is there an option to set the casing of the object fields?

This is very important because the API contracts are all in camelCase, so change all of then its a huge task.

Many thanks in advance.

**Comment by Melaninneal** [comment]
the response fields are based on the naming of the structs you create, does your structs have snake case?

**Comment by pavelnikolov** [comment]
Also the clients can rename fields as they see fit. For example:
```
person(id: "ahf5bb23==") {
    date_of_birth: dateOfBirth,
    first_name: firstName,
    last_name: lastName
}
```

**Comment by fuintis** [comment]
Sorry, my mistake.

Many thanks for your time!
