### ISSUE TITLE
Unable to use scalar Time for Inputs

### ISSUE THREAD

**Issue by Melaninneal** [graph-gophers/graphql-go#248]
It looks like when you try to use scalar time as an input, you get an error message "cant unmarshal <string> (string) as time.Time 

<img width="1331" alt="screen shot 2018-08-16 at 9 54 03 pm" src="https://user-images.githubusercontent.com/26153620/44267231-749b5400-a1fb-11e8-9745-a2a245245277.png">

**Comment by maxbeatty** [comment]
Make sure that string is RFC3339 compliant like "2006-01-02T15:04:05Z07:00" ([see source](https://github.com/graph-gophers/graphql-go/blob/4bf1651e09c2bc4fc2bc133dd657130c7e8ee7ec/time.go#L21-L43))

**Comment by Melaninneal** [comment]
<img width="1654" alt="screen shot 2018-08-17 at 6 37 41 pm" src="https://user-images.githubusercontent.com/26153620/44291621-7857c680-a24d-11e8-9379-80b9368cfc61.png">

still the same issue when i use compliant strings

**Comment by vetcher** [comment]
time.Time is not an available input type, you should not use it. Use graphql.Time instead

**Comment by pavelnikolov** [comment]
@vetcher is correct. You have to define `scalar Time` in your schema and use the type defined in this library https://github.com/graph-gophers/graphql-go/blob/master/time.go#L11
