### ISSUE TITLE
is not a pointer

### ISSUE THREAD

**Issue by u007** [graph-gophers/graphql-go#255]
hi

im trying to return slices of a model as an attribute of another model.
```
func (r *userResolver) Roles() *[]*model.Role {
	// var roles []*model.Role
	roles := make([]*model.Role, 0)

	return &roles
}
```
there were no error in the code, except im receiving panic indicating:
```
panic: field "Roles": model.Role is not a pointer
```

**Comment by aaahrens** [comment]
What does the user resolver look like?

**Comment by vetcher** [comment]
I think problem in struct `model.Role` methods:
They all should be like `func (r *model.Role) A(...)...` and not `func (r model.Role) ...)`
So that mean, they all should be with pointer receiver

**Comment by u007** [comment]
User struct look like this:
```

type User struct {
	UID               string `json:"uid"`
	Email             string `json:"email" db:"email"`
	Username          string `json:"username" db:"username"`
	Password          string `json:"password"`
	EncryptedPassword string `json:"encrypted_password"`
	First_name        string `json:"first_name" db:"first_name"`
	Last_name         string `json:"last_name" db:"last_name"`
	IPAddress string    `json:"ip_address" db:"ip_address`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Roles     *[]*Role  `json:"roles"`
}

```

**Comment by u007** [comment]
> I think problem in struct `model.Role` methods:
> They all should be like `func (r *model.Role) A(...)...` and not `func (r model.Role) ...)`
> So that mean, they all should be with pointer receiver
> @u007

Hi @vetcher , where did you see me using 
```func (r model.Role) ...)``` ?

**Comment by aaahrens** [comment]
does your userResolver look like this:

`type UserResolver struct {
	*User
}`

**Comment by u007** [comment]
nvm, i resolved to use [Role!] and it works.
make sense that slice returned could be nil, but the Role should be a valid role

```
type userResolver struct {
	u                *model.User
}

func (r *userResolver) Roles() *[]roleResolver {
	var roles []roleResolver
	if r.u.Roles == nil {
		return &roles
	}

	userRoles := *r.u.Roles
	for i := range *r.u.Roles {
		roles[i] = roleResolver{
			role: userRoles[i],
		}
	}
	return &roles
}

```

**Comment by koenpunt** [comment]
> nvm, i resolved to use [Role!] and it works.

Makes sense, a nullable graphql field should be defined as pointer, because those can be nil too.
