### ISSUE TITLE
Why is there so many open PR's with no conflicts and resolved discussion

### ISSUE THREAD

**Issue by aaahrens** [graph-gophers/graphql-go#257]
Just like the title says, it's concerning that there are so many open PR's that solve performance or compliance problems, like #102  #218 . It's really strange to see discussion about a PR then not merge or deny it.

edit: Grammar was bad

**Comment by pavelnikolov** [comment]
Hello @aaahrens 
I can assure you that the library is now actively maintained again and all future issues/PR will be responded promptly. I am sorry for the huge delay on some existing PRs.
It will take some time to go through all the old issues/PRs. Thank you for your patience.
Any feedback and contributions are highly appreciated.

P.S. _The current priority is subscriptions_
