### ISSUE TITLE
Error if a resolver returns invalid enum value

### ISSUE THREAD

**Issue by gracenoah** [graph-gophers/graphql-go#262]
Right now resolvers that return enums can return any string. This can cause issues for clients that expect the server to return one of a set of known values. It would be useful to have the resolver fail more quickly on the server side in this scenario instead of failing when the client interprets the response.

**Comment by vetcher** [comment]
right now golang does not have enums, so that if your server returns not available value then you handle enums values not as 'enums' really.
I handle enums in this way:
write a `enums.proto` file and use `protoc` and `protoc-gen-go` to generate enums
```proto
syntax = "proto3";

option go_package = "resolver";

enum DayOfWeek {
    // For copability with proto2
    UNKNOWNDay = 0;
    MONDAY = 1;
    TUESDAY = 2;
    WEDNESDAY = 3;
    THURSDAY = 4;
    FRIDAY = 5;
    SATURDAY = 6;
    SUNDAY = 7;
}

```
and then write methods for graphql
```go
//go:generate protoc --go_out=. enums.proto

func (x DayOfWeek) ImplementsGraphQLType(name string) bool { return name == "DayOfWeek" }
func (x DayOfWeek) MarshalJSON() ([]byte, error)           { return []byte(x.String()), nil }
func (x *DayOfWeek) UnmarshalGraphQL(input interface{}) error {
	p, ok := input.(string)
	if !ok {
		return fmt.Errorf("wrong type, expecting string")
	}
	v, ok := DayOfWeek_value[p]
	if !ok {
		return fmt.Errorf("unacceptable enum value %s", p)
	}
	*x = DayOfWeek(v)
	return nil
}

```

**Comment by gracenoah** [comment]
Thanks for the tip! I might use this!

This doesn't solve my problem completely though. The problem existing even in this case. If you define a different set of enum values in your protobufs vs in the graphql schema, it's possible to return an invalid (based on the schema) result to the client. I would prefer this to be a caught as a server error because it's really the server's fault.

**Comment by vetcher** [comment]
I think, we can find plugin for protoc which generates graphql enums. 
btw its not hard to make your own plugin for protoc

**Comment by vetcher** [comment]
also, this lib allows to bind enums not only to strings but ints or any other type you want

**Comment by pavelnikolov** [comment]
@gracenoah is this causing problems for your applications? We've been using a lot of enums in our projects and we have never faced this problem so far. Isn't this something that you can catch with unit tests? Or is your data coming from an external system (e.g. a datastore or a service) which is unpredictable?
We also map values between ProtoBuf and GraphQL in a very similar way to what @vetcher has shown...
I think that it is up to the developers to decide how to handle this and I will close this issue. Feel free to reopen the issue or raise a PR if you have a better idea how this can be handled.
