### ISSUE TITLE
Load in batches

### ISSUE THREAD

**Issue by marczahn** [graph-gophers/graphql-go#263]
Hi,

first: I like this library very well. But I am wondering if it is somehow possible to fetch entities in batches. 

Example: There is a list of users and each user can have multiple comments. When I load a list of users I would like to avoid loading the comments for each user separately but "collecting" the user ids and fetch the comments in one batch.

**Comment by vetcher** [comment]
check right there https://github.com/graph-gophers/dataloader

**Comment by marczahn** [comment]
I saw this. But how can I use it for the described purpose? When I understood it correctly, I walk through every resolver separately. So how do I collect the user ids for fetching the comments?

**Comment by vetcher** [comment]
in batch func you describe, how to get all keys in one request
```go
// setup batch function
batchFn := func(ctx context.Context, keys dataloader.Keys) []*dataloader.Result {
  var results []*dataloader.Result
  // do some aync work to get data for specified keys
  // append to this list resolved values
  return results
}
```

and when you call `loader.Get` it gets one result of a batch
```go
result, err := loader.Load(context.TODO(), dataloader.StringKey("some key"))()
if err != nil {
	// handle error
}
```

to understand it in easy way, think that dataloader has a global query of requested (by `Get` method) ids and then, in one moment, calls `batchFunc` to clear query and get all stuff

**Comment by marczahn** [comment]
Mh... Maybe we are cross talking. Situation is:

I have the customers loaded already. Now for every customer the commentResolver is executed. Let's say we have three users. This means - for now - I have three time to load comments.

I would like to have sth. like
```
getCommentsForUserIDs([]... userIDs)
```
In each commentresolver I pick the user's comments out of this list.

The problem I have is where to collect the user ids from the three commentresolvers to run getCommentsForUserIDs

**Comment by marczahn** [comment]
Nevermind - I got it :-) Thank you

**Comment by marczahn** [comment]
Ok, I tried this. But the dataloader loads all items sequentially - Which is obvious, since the resolvers are executed sequentially

**Comment by vetcher** [comment]
this library can execute resolvers concurrenly (and as I remember, lib do it by default), so, in theory, dataloader works fine. Of couse, when you execute sequentially dataloader will be useless

**Comment by marczahn** [comment]
I checked it and the batch size was always one. But I found another implementation which is even type safe and works very well -> https://github.com/vektah/dataloaden
