### ISSUE TITLE
Add example of custom errors

### ISSUE THREAD

**Issue by pavelnikolov** [graph-gophers/graphql-go#274]
Now that #272 has been merged it would be nice to have an example in the `errors` package which appears here https://godoc.org/github.com/graph-gophers/graphql-go/errors.
I think that input validation error(s) sounds like a good idea.

**Comment by hjf0416** [comment]
what's status for this one? I want to add extensions in my own app but not sure how to

**Comment by pavelnikolov** [comment]
The library supports it, we do not have a good example yet. The unit test is descriptive enough. PRs to improve the documentation or add an example are welcome. All errors that implement this interface:

```go
type ResolverError interface {
	error
	Extensions() map[string]interface{}
}
```

will return the extensions in the error output.
