### ISSUE TITLE
Whole object is null, when error returned with some value

### ISSUE THREAD

**Issue by 0xTanvir** [graph-gophers/graphql-go#275]
I was trying to return a type/object with error, so that I can debug my error from front-end, but it seems when I return any value into error then the whole object always return as `null` :( but if I return error as `nil` then it return object's value.

![problem](https://user-images.githubusercontent.com/18065424/47166578-572f5700-d31e-11e8-8b71-0cafafbaaa23.png)

**Comment by baba2k** [comment]
Same problem by me

**Comment by sanae10001** [comment]
https://github.com/graph-gophers/graphql-go/blob/995849d5bff2932ba449bea0c7cf0638d7f69f70/internal/exec/exec.go#L209

In fact, this is a tricky problem that is difficult to solve according to the current code implementation.

**Comment by svanburen** [comment]
this is part of the GraphQL spec:

https://facebook.github.io/graphql/June2018/#sec-Data

>If an error was encountered during the execution that prevented a valid response, the data entry in the response should be null.

**Comment by Anufant** [comment]
> this is part of the GraphQL spec:
> 
> https://facebook.github.io/graphql/June2018/#sec-Data
> 
> > If an error was encountered during the execution that prevented a valid response, the data entry in the response should be null.

But the spec contains phrase:

> A response may contain both a partial response as well as encountered errors in the case that a field error occurred on a field which was replaced with null.

And there are few examples with partial data and errors in one response later in section 7.1.2 of specification. 
So it's not so evident

**Comment by VincentVW** [comment]
@svanburen agree on resolving 1 instance, but this also occurs on returning a list and there I'm not sure if it should...

When you have a list of 10 items and 9 resolve correctly, and the tenth throws an error. Should you still be forced to give a null back while the 9 sub resolvers did produce a valid response?

**Comment by svanburen** [comment]
@VincentVW https://graphql.github.io/graphql-spec/June2018/#example-90475 - I'd agree that you shouldn't be forced to give `null` back in that situation.

**Comment by pavelnikolov** [comment]
I'm closing this issue as this is part of the spec requirements. @VincentVW if you think that the lib is violating the spec for lists I'd be happy to reopen the issue. A failing test would be more than appreciated.
