### ISSUE TITLE
Update Parser to latest spec.

### ISSUE THREAD

**Issue by smitt04** [graph-gophers/graphql-go#279]
It looks like the parser doesn't support the latest spec for descriptions. Using comments `#` works but that is deprecated in favor of string literals. https://facebook.github.io/graphql/June2018/#sec-Descriptions

I get the following as an error though

```
[14:12:05.106] panic: graphql: syntax error: unexpected "\"\"", expecting Ident (line 262, column 3)

goroutine 1 [running]:
[14:12:05.109] bitbucket.hsdp.io/dk/api/vendor/github.com/graph-gophers/graphql-go.MustParseSchema(0xc00031c000, 0x273c, 0x9d0d80, 0xc0003f60c8, 0x0, 0x0, 0x0, 0x7c000000009b3720)
	/go/src/bitbucket.hsdp.io/dk/api/vendor/github.com/graph-gophers/graphql-go/graphql.go:56 +0xb1
main.main()
	/go/src/bitbucket.hsdp.io/dk/api/server.go:40 +0x121
```

**Comment by janflyborg** [comment]
If I'm not totally wrong, you will get this particular feature when this PR is merged:
https://github.com/graph-gophers/graphql-go/pull/269

**Comment by pavelnikolov** [comment]
@janflyborg you are correct that PR got merged and it covers the requested functionality.
