### ISSUE TITLE
A helpful scalars library

### ISSUE THREAD

**Issue by sanae10001** [graph-gophers/graphql-go#288]
https://github.com/sanae10001/graphql-go-extension-scalars
@pavelnikolov Can i transfer the repository to graph-gophers?

**Comment by pavelnikolov** [comment]
@sanae10001 I don't think that this should be a separate project. You can add it to the `/examples` folder. However, it'd be better if you remove the external dependencies for the unit tests.

**Comment by mgyong** [comment]
@pavelnikolov How do you use the extension scalars from the library https://github.com/sanae10001/graphql-go-extension-scalars with graphql-go? Can you guide me a little? Thanks

**Comment by jerbob92** [comment]
@pavelnikolov thanks for the info! But it's still not really clear to me how to make them register as a scalar in graphql-go
