### ISSUE TITLE
New resolver per request?

### ISSUE THREAD

**Issue by vimalloc** [graph-gophers/graphql-go#290]
I'm curious if it's possible to use a new resolver for each request? I can do everything I need to with contexts already, but I don't really like having to pull out and cast all that information (current user, dataloader, etc) everywhere that I need it. If I could shove all of that information into a new resolver that was used for an incoming request, I think the code would be more type safe and easier to write unit tests for.

**Comment by pavelnikolov** [comment]
I am not sure that I understand your request. Can you give a pseudo-code example?

**Comment by pavelnikolov** [comment]
@vimalloc thanks for your interest in the project. I think that the library has to remain as minimalistic and implementation agnostic as possible. You have to use some kind of a dynamic resolver. I have had a similar use-case in the past and I have used the `context` arg. The library has to be transport agnostic as well. There might be clients that do not use HTTP, so passing the incoming request as an argument doesn't sound like a good idea. For now the best solution is to use the context. I'm closing this issue for now as there isn't an immediate solution with the current implementation. Implementing this would introduce significant amount of complexity and it doesn't add much value to the project.
