### ISSUE TITLE
Got is not a slice error

### ISSUE THREAD

**Issue by PhmNgocNghia** [graph-gophers/graphql-go#295]
Here is mine code:
```
func (r *GetUserResolver) Users() *[]*UserResolver {
	l := make([]*UserResolver, len(r.InputUsers))
	for i := range l {
		l[i] = &UserResolver{
			User: r.InputUsers[i],
		}
	}
	return &l
}

type UserResolver struct {
	User models.User
}

func ID(r UserResolver) graphql.ID {
	return graphql.ID(r.User.ID)
}
```

Error:
```
panic: *[]*user.UserResolver is not a slice
        returned by (*user.GetUserResolver).Users
        returned by (*graphql.RootResolver).GetUser
```

I return a slice but it say it's not a slice...

**Comment by bsr203** [comment]
probably an issue with schema definition of required field

 users: [User!]  => *[]* UserResolver

users: [User!]! => []* UserResolver

**Comment by bsr203** [comment]
`users: [Int]!,` . did you mean to write `users: [User]!,`. IF you indeed is trying to serve ids, may be `func (r *GetUserResolver) Users() *[]int32`

**Comment by pavelnikolov** [comment]
@PhmNgocNghia do you still have an issue? I'm closing this issue since I think that this is an error on your end as @bsr203 has suggested above. Feel free to open a new issue in case you find a bug with the library.
