### ISSUE TITLE
getting json from schema connection list or single object 

### ISSUE THREAD

**Issue by u007** [graph-gophers/graphql-go#303]
hi,

ive a userResolver,
is there a way i could get json from userResolver directly?

what about usersConnectionResolver?

**Comment by pavelnikolov** [comment]
Do you have an example? I'm not sure I understand your question...

**Comment by u007** [comment]
i meant example:
```
res := userResolver{user: UserObject}
getJSON(res)
```
should return 
```
{
  first_name: '...',
  last_name: '...',
  email: '...@...com'
}
```

conn := userConnectionResolver{users: Users}
getJSON(conn)
```
{
   edges: [
      {
        cursor: '...',
        node: { id: '', first_name: '...', ... }
      },
      ...
   ]
}
```

**Comment by pavelnikolov** [comment]
This question is not related to the library in any way. If you want the JSON that corresponds to some query, you need to execute the query against some schema. Otherwise, you can just `json.Marshal` your struct and you'll get the serialised object.
