### ISSUE TITLE
Custom slice resolver

### ISSUE THREAD

**Issue by koliyo** [graph-gophers/graphql-go#306]
It would be nice if it was possible to use a custom slice resolver type, to avoid copying the entire slice if the type needs to be transformed.
```go
	case *common.List:
		if resolverType.Kind() != reflect.Slice {
			return nil, fmt.Errorf("%s is not a slice", resolverType)
		}
```

it should be possible to use some custom listUnmarshal interface like for scalar types
```go
	case packer.Unmarshaler:
		implementsType = r.ImplementsGraphQLType(t.Name)
}
```

**Comment by pavelnikolov** [comment]
Can you, please, give a more detailed example?

**Comment by koliyo** [comment]
Ok, if I have a struct which is not directly resolvable
```go
type Foo struct {
  bar int64
  ...
}
```

This may come from another package, so I may not be able to extend resolve functions directly on the struct. So instead I create a wrapper resolver

```go
type GqlFoo struct {
  Foo
}

func (f GqlFoo) Bar() int32 {
return int32(f.bar)
}
```

and I simply wrap this in my query resolvers

```go
func (_ *query) GetFooWithId(ctx context.Context, args *struct {
  Id string
}) GqlFoo {
  foo := getFoo(id)
  return GqlFoo{foo}
}
```

but if I have a list of `Foo` I must copy the entire list

```go
func (_ *query) GetAllFoos(ctx context.Context) []GqlFoo {
  gqlFooList := make([]GqlFoo, len(allFoos))
  for i, v := range allFoos {
    gqlFooList[i] = GqlFoo{v}
  }
  return gqlFooList
}
```


What if I instead could have a custom List-resolver, that is called for each element to be resolved, and there create wrapper resolvers dynamically. Something like this.

```go
type GqlFooList {
  fooList []Foo
}

func (f GqlFooList) GetElement(i index) GqlFoo {
  return GqlFoo{f.fooList}
}
```

then my `GetAllFoos` query resolver is simply

```go
func (_ *query) GetAllFoos(ctx context.Context) GqlFooList {
  return GqlFooList{allFoos}
}
```

and I do not have to copy the list.

The custom List resolver would have to follow some interface, getting the length of the list and getting elements by index would probably be sufficient.

**Comment by pavelnikolov** [comment]
Well, if the list is super small it shouldn't make a big difference, no? And if the list is huge, can't you just use GraphQL subscription instead of query? This way you'll be able to stream the items one by one. 🤔

**Comment by koliyo** [comment]
Yeah, it is not really a big issue. The large lists was my concern, but then pagination or streaming should be used as you say.

**Comment by pavelnikolov** [comment]
I'm closing this issue for now. Feel free to reopen if you cannot solve it in any other way.
