### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by pavelnikolov** [graph-gophers/graphql-go#307]
Improve resolvers documentation and add a link to the field resolvers example.

**Comment by souvik3333** [comment]
Hi, Can I work on this?

**Comment by pavelnikolov** [comment]
Yes, you can. What parts of it do you want to cover? I was planning to add short descriptions for different schema options. Another thing that I was planning to do is create an example markdown document which lists community examples (move them from the README.md) and another one for companies that use this library. PRs are welcome.

**Comment by souvik3333** [comment]
I was thinking about adding an explanation from basics like how it works with schema examples. When I started using this I had quite problems figuring how this work. I think Social and starwars examples are a bit hard for first-time graphql user.
