### ISSUE TITLE
Optional slices must be a pointer

### ISSUE THREAD

**Issue by kevinwmiller** [graph-gophers/graphql-go#308]
I'm using the models generated by Prisma, and optional slices are not outputted as pointers because slices are already nilable values. However, when I try to use the model with graphql-go, I receive the following error
```bash
panic: field "Where": field "IDIn": []string is not a pointer
```
Is this behavior correct? The issue is resolved if I manually change the slices in my model to be pointers to slices, but this does not seem like the correct solution because a pointer to a slice does not make much sense.

I looked through the graphql-go code, and it looks like there are no special considerations for lists and any optional parameters must be pointers. Is this something that can be fixed? I can make the change, but I just want to check if there is a reason for the current behavior.

Here is a snippet of my model:

```go
type SpaceWhereInput struct {
	ID                       *string           `json:"id,omitempty"`
	IDNot                    *string           `json:"id_not,omitempty"`
	IDIn                     []string          `json:"id_in,omitempty"`
	IDNotIn                  []string          `json:"id_not_in,omitempty"`
	IDLt                     *string           `json:"id_lt,omitempty"`
	IDLte                    *string           `json:"id_lte,omitempty"`
	IDGt                     *string           `json:"id_gt,omitempty"`
	IDGte                    *string           `json:"id_gte,omitempty"`
	IDContains               *string           `json:"id_contains,omitempty"`
	IDNotContains            *string           `json:"id_not_contains,omitempty"`
	IDStartsWith             *string           `json:"id_starts_with,omitempty"`
...
```
Here is the associated graphql model
```graphql
input SpaceWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
...
```

**Comment by pavelnikolov** [comment]
I do not see any problem with that. Indeed there are some cases when you would want to distinguish between empty slice and a `nil` slice. However, these cases are extremely rare. In the vast majority of cases you should have a non-nullable slice of non-nullable elements, for example:

```graphql
id_in: [ID!]!
```

**Comment by duckbrain** [comment]
There is a difference between a nil slice and a nil pointer to a slice. What I think @kevinwmiller is getting at is that a pointer to a slice doesn't make sense because a slice is already a pointer (like channels and maps), so you can still easily distinguish between a nil slice and an empty slice.

```
package main

import "fmt"

func main() {
	var ptest *[]string
	var test []string
	fmt.Println("zero values")
	fmt.Println("it's nil", ptest == nil)
	fmt.Println("it's nil", test == nil)
	ptest = &test
	fmt.Println("ptest = &test")
	fmt.Println("it's nil", ptest == nil)
	fmt.Println("it's nil", test == nil)
	fmt.Println("it's nil", *ptest == nil)
	test = make([]string, 0)
	fmt.Println("test = make([]string, 0)")
	fmt.Println("it's nil", ptest == nil)
	fmt.Println("it's nil", test == nil)
	fmt.Println("it's nil", *ptest == nil)
}
```

Output

```
zero values
it's nil true
it's nil true
ptest = &test
it's nil false
it's nil true
it's nil true
test = make([]string, 0)
it's nil false
it's nil false
it's nil false
```

His slices could be nil, but if he goes with `id_in: [ID!]!` and they are nil, it will error out because it's not declared that way.

**Comment by pavelnikolov** [comment]
@kevinwmiller When I started using the library it was already like this. We need to be careful with changes like this. Your comment makes total sense, however, changing that would probably introduce a breaking change for existing users of the library, right? At this point I would be skeptical with any type of breaking changes. Pointer to a slice seems like a good workaround for now. Maybe we need to make this a schema option and allow users to override the default behaviour 🤔
I'd be happy to accept a PR if it doesn't introduce a breaking change...

**Comment by kevinwmiller** [comment]
@pavelnikolov I completely agree that making a breaking change to accommodate this issue would be unacceptable. I can take a closer look and see if I can come up with a solution that does not break existing functionality

**Comment by kevinwmiller** [comment]
Should the issue be reopened or do you want to leave it marked as closed?

**Comment by pavelnikolov** [comment]
TBH this already has a simple workaround that doesn't cause too much pain. I'd be happy to leave it closed. If this is blocking you or cause a serious problem, then I'd reopen it. It is not really a bug, it's more like a decision that was made initially and now we have to stick to it. The only possible way to change it is with a opt-in schema option at creation time. Otherwise, changing this behaviour would break compatibility with existing users...
I'd consider merging a PR that adds an opt-in fix.
