### ISSUE TITLE
Feature Request: Persisted Queries

### ISSUE THREAD

**Issue by trahloff** [graph-gophers/graphql-go#311]
API Caching on CDN level is nearly impossible since there is no real support for persisted queries (=> GET requests).

Implementing the persisted queries concept would have a positive impact on usability, performance and security. 

For reference: [Persisted Queries in NodeJS](https://blog.apollographql.com/persisted-graphql-queries-with-apollo-client-119fd7e6bba5)

**Comment by pavelnikolov** [comment]
The library is low level and should not care about persisted queries. It's up to the developers to decide how to use the library. Remember this is not a fully featured GraphQL framework. It is just a minimalistic library that can parse/validate/execute queries. I am closing this issue for now.
