### ISSUE TITLE
Add option to turn off html escaping of response json data

### ISSUE THREAD

**Issue by Anufant** [graph-gophers/graphql-go#312]
Golang standard library json encoder escapes some html symbols during encoding by default.
So we get slightly modified information, for example in URLs with  "&" character.

**Comment by pavelnikolov** [comment]
This is not a problem with this library and will close this issue as there are workarounds explained elsewhere. For example: https://stackoverflow.com/a/28596225 
I would reconsider changing this, though, as it can make some browsers "unhappy" about your JSON.
