### ISSUE TITLE
Access context in Unmarshaler

### ISSUE THREAD

**Issue by hampusohlsson** [graph-gophers/graphql-go#319]
Would be great if there was a way to access the context in the `UnmarshalGraphQL` method for custom scalars.

We have a pretty sizeable GraphQL codebase built using this project, with a few custom scalars. In our use case, we ship all errors to StackDriver, and in doing so we need to access things like trace id and original request that is attached to the context in the http handler. Right now it's not possible to access the context from within that method, thus we can't annotate errors with the required information.

I think it makes sense to use the same logic as the resolvers, either you take a context or not as the first argument. Would something like this be possible?

```golang
type ContextUnmarshaler interface {
	ImplementsGraphQLType(name string) bool
	UnmarshalGraphQL(ctx context.Context, input interface{}) error
}
```

**Comment by pavelnikolov** [comment]
Hi @hampusohlsson, I think that this is not a great idea. Ideally, the unmarshaller code should not have any side effects. You can handle the error in the resolver itself and send it anywhere you want. I don't think that the library should allow that.
Out of curiosity how do you implement the `UnmarshalGraphQL` interface? 
I'm closing this issue for now but I'd be interested to know more details.

**Comment by hampusohlsson** [comment]
Hi @pavelnikolov 

> Out of curiosity how do you implement the UnmarshalGraphQL interface?

Right now I have to implement it without the context, so we cannot log the user who caused the error, what the query was or any related trace id's.

To give you more information about why I suggested this proposal.. on application startup we initialize tracing, a custom Logger and a StackDriver error reporting client, which are attached to the request context in the query handler, together with JWT information about the user. 

We then have a custom error reporting library `gqlerrors`, that is implementing the `extensionser` interface so we can expose different status codes, and is using the context to retrieve/log the query, trace id's and the user that caused the error.

Ideally I would want to use the `UnmarshalGraphQL` like below...

```go
func (s *BarScalar) UnmarshalGraphQL(ctx context.Context, input interface{}) error {
    //  ...
    if err != nil {
        return gqlerrors.BadRequest(ctx, "Invalid bar input")
    }
}
```

...this would return an error like this, while logging the user+query that caused the error to our 3rd party error logging.
```
{
  "errors": [
    {
      "message": "Invalid bar input",
      "path": [
        "foo",
        "bar"
      ],
      "extensions": {
        "statusCode": 400,
        "traceId": "e9d33bfdec32cbf7e8c8495a66046ff4"
      }
    }
  ],
  "data": {
    "foo": {
      "id": "a2d0a37e-5d90-4b96-bc9e-ff4b6e08df1c",
      "bar": null
    }
  }
}
```

**Comment by pavelnikolov** [comment]
You can write some custom `UnmarshalGraphQL` function, which accepts `ctx` and an `Unmarshaller`. Then you can enrich the error from the underlying `UnmarshalGraphQL` method. That way all your resolvers will use the same function and you'll have to maintain it in only one place but you will use it everywhere. 🤔

**Comment by hampusohlsson** [comment]
Just to clarify, is this what you are suggesting? Bypassing the native error in the unmarshaller...

```go
type UUID struct {
    Value uuid.UUID
    Error error
}

func (u *UUID) UnmarshalGraphQL(input interface{}) error {
    //  ...
    if err != nil {
        u.Error = err
        return nil
    }
}

func (u *UUID) Validate(ctx context.Context) error {
    if u.Error != nil {
        return gqlerrors.BadRequest(ctx, "Invalid UUID input")
    }
    return nil
}
```

... and then you'd have to call `.Validate(ctx)` from each resolver? It certainly works but I think it makes a less intuitive API. 

I accept your decision if you don't think this is a good idea :) but maybe valuable information for other people trying to productionize their graphql apps

**Comment by pavelnikolov** [comment]
Well, I was suggesting another thing, but I haven't tried it yet. I have to try it first to double check if it would work. Your solution seems like a good workaround.
