### ISSUE TITLE
Passing map as a resolvers

### ISSUE THREAD

**Issue by MatisiekPL** [graph-gophers/graphql-go#320]
Hello,
I want to pass map[string]interface{} as a resolvers.
Can I do it? If yes, how?

Thanks,
Mateusz Woźniak

**Comment by romshark** [comment]
@MatisiekPL What exactly are you even trying to do? Please provide a more detailed explanation of what you're doing, how you're doing it, what you want to achieve eventually and what problems you face.

**Comment by pavelnikolov** [comment]
@MatisiekPL AFAIK, this is not even allowed by the GraphQL spec. Instead, you should try using arrays. I'm closing this issue as the requested feature doesn't conform to the GraphQL spec.
