### ISSUE TITLE
Support for embedded struct type in resolver

### ISSUE THREAD

**Issue by gxb5443** [graph-gophers/graphql-go#331]
I would like my resolver to expand on an existing struct type, like from another package, when using `UseFieldResolvers`. To do that, I compose the objects by embedded the base struct inside the resolver struct. However, this doesn't compile because it looks like graphql-go only traverses the first level of fields to find the one that satisfies the schema. This would be helpful so I don't have to implement tedious resolver methods for every field.

```golang
package resolvers

import "github.com/gxb5443/project1/users"

type AdminResolver struct {
  users.Admin
}
```

**Comment by jseibert** [comment]
Strongly agreed. This would allow composing GraphQL types from DB types while keeping them separate, without requiring tons of boilerplate.

**Comment by eloyekunle** [comment]
In progress: #338

**Comment by dnutels** [comment]
This is a fairly crucial topic. Ambiguity should be resolved in the same manner all other issues with schema -> type are resolved, by panicing on mismatch, just like a missing resolver does. 

Separating the types, which should really be auto-generated and external to the client code, from the resolvers is an extremely valuable thing.
