### ISSUE TITLE
Func to determine if query is mutating or non-mutating.

### ISSUE THREAD

**Issue by sbunce** [graph-gophers/graphql-go#332]
In our application we need to determine if queries are mutating or non-mutating so we can determine if we should set the "ReadOnly" option true on our Postgres database transaction.
https://golang.org/pkg/database/sql/#TxOptions

Would it be useful to have a func to do this?

**Comment by duckbrain** [comment]
We typically use different structs for queries and mutations, then use embedding to combine them for GraphQL Go.

```go
type resolvers struct {
    mutations
    queries
}

type mutations struct {
}

type queries struct {
}
```

You could then have `mutations` and `queries` implement an interface that indicates read only or not and pass it into wherever you need.

**Comment by pavelnikolov** [comment]
Typically all mutation resolvers are mutating. So you can easily do this outside of the library. As @duckbrain has pointed out this can be done in your mutation resolvers. I'd like to keep the library as minimalistic as possible. I'm closing this issue as it's not directly related to the library.
