### ISSUE TITLE
Support Int64 in ID Field

### ISSUE THREAD

**Issue by rchatrath7** [graph-gophers/graphql-go#333]
We're running into a case where we have a request to a resolver that has a `graphql.ID` field but the ID sent in the request is larger than a 32bit integer. This in turn causes a panic with `strconv.ParseInt value out of range`. For instance, sending a request with `ID: 5542805574`, results in: 
`"graphql: panic occurred: strconv.ParseInt: parsing \"5542805574\": value out of range"`. 

Taking a look at `graphql.ID`, an additional case could be added for `int64`.

**Comment by pavelnikolov** [comment]
In JavaScript the integers are generally 32bit. Therefore in GraphQL integers are also 32bit. Is it possible that you wrap the field in quotes and treat it like a string? Is it a hard requirement that the field is `int64`?

**Comment by rchatrath7** [comment]
We chose to make the field a string. It just seems like a small oversight to not be able to support integers larger than 32bit -- though I can understand why GraphQL spec would be that way if Javascript ints are usually 32bit. We still end up parsing this to a 64bit int later in the application, but I don't feel strongly about `graphql.ID` needing to support `int64`

**Comment by pavelnikolov** [comment]
Thank you. I'll close the issue for now
