### ISSUE TITLE
use of internal package github.com/graph-gophers/graphql-go/internal/ not allowed

### ISSUE THREAD

**Issue by marcoippolito** [graph-gophers/graphql-go#335]
As described here: https://github.com/zohararad/bee-gorm-graphql/issues/7

I got this error message: use of internal package github.com/graph-gophers/graphql-go/internal/ not allowed:

In my Ubuntu 18.04.01 Server Edition I git cloned the bee-gorm-graphql repository, and followed the indications to run the app:

    marco@pc01:~/go/src/bee-gorm-graphql$ yarn install
    yarn install v1.16.0
    [1/5] Validating package.json...
    [2/5] Resolving packages...
    [3/5] Fetching packages...
    info fsevents@1.0.15: The platform "linux" is incompatible with this module.
    info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it 
    from installation.
    [4/5] Linking dependencies...
    [5/5] Building fresh packages...
    Done in 56.60s.

    marco@pc01:~/go/src/bee-gorm-graphql$ glide up
    [WARN]	The name listed in the config file (github.com/zohararad/bee-gorm-graphql) does 
    not match the current location (bee-gorm-graphql)
    [INFO]	Downloading dependencies. Please wait...
    [INFO]	--> Fetching updates for github.com/neelance/graphql-go
    [INFO]	--> Fetching updates for github.com/astaxie/beego
    [INFO]	--> Fetching updates for github.com/lib/pq
    [INFO]	--> Fetching updates for github.com/jinzhu/gorm
    [INFO]	--> Fetching updates for github.com/smartystreets/goconvey
    [INFO]	--> Detected semantic version. Setting version for github.com/jinzhu/gorm to v1.0
    [INFO]	--> Detected semantic version. Setting version for github.com/smartystreets/goconvey 
    to 1.6.3
    [INFO]	--> Detected semantic version. Setting version for github.com/astaxie/beego to v1.7.2
    [INFO]	Resolving imports
    [INFO]	--> Fetching updates for github.com/jinzhu/inflection
    [INFO]	--> Fetching updates for github.com/graph-gophers/graphql-go
    [INFO]	--> Fetching updates for github.com/opentracing/opentracing-go
    [INFO]	--> Fetching updates for github.com/jtolds/gls
    [INFO]	--> Fetching updates for github.com/smartystreets/assertions
    [INFO]	--> Fetching updates for github.com/gopherjs/gopherjs
    [INFO]	Downloading dependencies. Please wait...
    [INFO]	Setting references for remaining imports
    [INFO]	Exporting resolved dependencies...
    [INFO]	--> Exporting github.com/astaxie/beego
    [INFO]	--> Exporting github.com/lib/pq
    [INFO]	--> Exporting github.com/smartystreets/assertions
    [INFO]	--> Exporting github.com/jinzhu/gorm
    [INFO]	--> Exporting github.com/neelance/graphql-go
    [INFO]	--> Exporting github.com/jinzhu/inflection
    [INFO]	--> Exporting github.com/graph-gophers/graphql-go
    [INFO]	--> Exporting github.com/opentracing/opentracing-go
    [INFO]	--> Exporting github.com/smartystreets/goconvey
    [INFO]	--> Exporting github.com/jtolds/gls
    [INFO]	--> Exporting github.com/gopherjs/gopherjs
    [INFO]	Replacing existing vendor dependencies
    [INFO]	Project relies on 7 dependencies.

    marco@pc01:~/go/src/bee-gorm-graphql$ go get github.com/beego/bee

    marco@pc01:~/go/src/bee-gorm-graphql$ npm run build

    > bee-gorm-graphql@1.0.0 build /home/marco/go/src/bee-gorm-graphql
    > webpack --optimize-minimize --optimize-dedupe

    Hash: 0d9d76918d563f081cd9918eb5f903e20cef830e
    Version: webpack 1.14.0
    Child js:
        Hash: 0d9d76918d563f081cd9
        Version: webpack 1.14.0
        Time: 9090ms
            Asset       Size  Chunks             Chunk Names
            app.js    22.8 kB       0  [emitted]  app
            vendor.js     435 kB    1, 2  [emitted]  vendor, vendor.js
            components.css  334 bytes       0  [emitted]  app
            app.js.map     133 kB       0  [emitted]  app
            components.css.map   91 bytes       0  [emitted]  app
            vendor.js.map    2.89 MB    1, 2  [emitted]  vendor, vendor.js
           [0] multi vendor 64 bytes {1} [built]
            + 244 hidden modules

        WARNING in ./~/encoding/lib/iconv-loader.js
        Critical dependencies:
        9:12-34 the request of a dependency is an expression
         @ ./~/encoding/lib/iconv-loader.js 9:12-34
    
        WARNING in app.js from UglifyJs
        Dropping unused variable __vue_styles__ [./~/vue-loader!./~/eslint-loader!./static
    /js/App.vue:2,0]
        Dropping unused variable __vue_styles__ [./~/vue-loader!./~/eslint-loader!./static
    /js/components/layout/Sidenav.vue:2,0]
        Side effects in initialization of unused variable _h [./~/vue-loader/lib/template-
    compiler.js?id=data-v-406cea44!./~/vue-loader/lib/selector.js?type=template&index=0!./static
    /js/components/layout/Sidenav.vue:1,48]
        Side effects in initialization of unused variable _h [./~/vue-loader/lib/template-
    compiler.js?id=data-v-7da67e45!./~/vue-loader/lib/selector.js?type=template&index=0!./static
    /js/App.vue:1,48]
        Side effects in initialization of unused variable RECEIVE_USERS [./static/js/store/mutation-
    types.js:1,13]
        Side effects in initialization of unused variable SET_USER [./static/js/store/mutation-
    types.js:2,13]
        Side effects in initialization of unused variable UNSET_USER [./static/js/store/mutation-
    types.js:3,13]
        Side effects in initialization of unused variable CREATE_USER [./static/js/store/mutation-
    types.js:4,13]
        Side effects in initialization of unused variable UPDATE_USER [./static/js/store/mutation-
    types.js:5,13]
        Side effects in initialization of unused variable DELETE_USER [./static/js/store/mutation-
    types.js:6,13]
        Side effects in initialization of unused variable USER_SAVED [./static/js/store/mutation-
    types.js:7,13]
        Condition always true [./~/vuex/dist/logger.js:2,0]
        Dropping unused variable __vue_styles__ [./~/vue-loader!./~/eslint-loader!./static
    /js/components/sections/Home.vue:2,0]
        Side effects in initialization of unused variable _h [./~/vue-loader/lib/template-
    compiler.js?id=data-v-66222d1a!./~/vue-loader/lib/selector.js?type=template&index=0!./static
    /js/components/sections/Home.vue:1,48]
        Side effects in initialization of unused variable _c [./~/vue-loader/lib/template-
    compiler.js?id=data-v-66222d1a!./~/vue-loader/lib/selector.js?type=template&index=0!./static
    /js/components/sections/Home.vue:1,74]
        Side effects in initialization of unused variable _h [./~/vue-loader/lib/template-
    compiler.js?id=data-v-66222d1a!./~/vue-loader/lib/selector.js?type=template&index=0!./static
    /js/components/sections/Home.vue:3,45]
        Dropping unused variable __vue_styles__ [./~/vue-loader!./~/eslint-loader!./static
    /js/components/sections/Users.vue:2,0]
        Side effects in initialization of unused variable _h [./~/vue-loader/lib/template-
    compiler.js?id=data-v-6a9562a4!./~/vue-loader/lib/selector.js?type=template&index=0!./static
    /js/components/sections/Users.vue:1,48]
        Side effects in initialization of unused variable _h [./~/vue-loader/lib/template-
    compiler.js?id=data-v-6a9562a4!./~/vue-loader/lib/selector.js?type=template&index=0!./static
    /js/components/sections/Users.vue:43,45]
        Side effects in initialization of unused variable _h [./~/vue-loader/lib/template-
    compiler.js?id=data-v-6a9562a4!./~/vue-loader/lib/selector.js?type=template&index=0!./static
    /js/components/sections/Users.vue:51,27]
        Side effects in initialization of unused variable _h [./~/vue-loader/lib/template-
    compiler.js?id=data-v-6a9562a4!./~/vue-loader/lib/selector.js?type=template&index=0!./static
    /js/components/sections/Users.vue:57,27]
        Side effects in initialization of unused variable _h [./~/vue-loader/lib/template-
    compiler.js?id=data-v-6a9562a4!./~/vue-loader/lib/selector.js?type=template&index=0!./static
    /js/components/sections/Users.vue:59,27]
        Side effects in initialization of unused variable _h [./~/vue-loader/lib/template-
    compiler.js?id=data-v-6a9562a4!./~/vue-loader/lib/selector.js?type=template&index=0!./static
    /js/components/sections/Users.vue:65,27]
        Dropping unused variable __vue_styles__ [./~/vue-loader!./~/eslint-loader!./static
    /js/components/sections/users/Form.vue:2,0]
        Side effects in initialization of unused variable _h [./~/vue-loader/lib/template-
    compiler.js?id=data-v-71f82dff!./~/vue-loader/lib/selector.js?type=template&index=0!./static
    /js/components/sections/users/Form.vue:1,48]
        Side effects in initialization of unused variable _h [./~/vue-loader/lib/template-
    compiler.js?id=data-v-71f82dff!./~/vue-loader/lib/selector.js?type=template&index=0!./static
    /js/components/sections/users/Form.vue:149,45]
        Side effects in initialization of unused variable _h [./~/vue-loader/lib/template-
    compiler.js?id=data-v-71f82dff!./~/vue-loader/lib/selector.js?type=template&index=0!./static
    /js/components/sections/users/Form.vue:158,27]
        Side effects in initialization of unused variable _h [./~/vue-loader/lib/template-
    compiler.js?id=data-v-71f82dff!./~/vue-loader/lib/selector.js?type=template&index=0!./static
    /js/components/sections/users/Form.vue:167,27]
        Side effects in initialization of unused variable _h [./~/vue-loader/lib/template-
    compiler.js?id=data-v-71f82dff!./~/vue-loader/lib/selector.js?type=template&index=0!./static
    /js/components/sections/users/Form.vue:176,27]
    
        WARNING in vendor.js from UglifyJs
        Side effects in initialization of unused variable f [./~/vue/dist/vue.common.js:5888,0]
        Condition always true [./~/vuex/dist/vuex.js:7,0]
        Side effects in initialization of unused variable parse_url [./~/node-fetch/index.js:8,0]
        Condition always true [./~/url/~/punycode/punycode.js:511,0]
        Dropping unreachable code [./~/url/~/punycode/punycode.js:518,2]
        Side effects in initialization of unused variable freeExports [./~/url/~/punycode
    /punycode.js:5,0]
        Side effects in initialization of unused variable freeModule [./~/url/~/punycode
    /punycode.js:7,0]
        Dropping unused variable key [./~/url/~/punycode/punycode.js:56,0]
        Dropping unused function forEach [./~/readable-stream/lib/_stream_duplex.js:71,0]
        Side effects in initialization of unused variable EE [./~/readable-stream
    /lib/_stream_readable.js:20,0]
        Side effects in initialization of unused variable Buffer [./~/readable-stream/lib/internal
    /streams/BufferList.js:3,0]
        Dropping unused variable self [./~/browserify-zlib/src/index.js:494,0]
        Child extract-text-webpack-plugin:
                 + 2 hidden modules
        Child extract-text-webpack-plugin:
                + 2 hidden modules
        Child extract-text-webpack-plugin:
                + 2 hidden modules
    Child css:
        Hash: 918eb5f903e20cef830e
        Version: webpack 1.14.0
        Time: 10208ms
                                         Asset                         Size  Chunks             Chunk Names
          674f50d287a8c48dc19ba404d20fe713.eot       166 kB                    [emitted]  
          af7ae505a9eed503f8b8e6982036873e.woff2     77.2 kB                  [emitted]  
          fee66e712a8a08eef5805a46892932ad.woff        98 kB                    [emitted]  
          b06871f281fee6b241d60582ae9369b9.ttf         166 kB                    [emitted]  
          912ec66d7572ff821749319396470bde.svg       444 kB                    [emitted]  
          app.css                                                          113 kB    0, 0  [emitted]  app, app
          app.css.map                                                    84 bytes    0, 0  [emitted]  app, app
          + 10 hidden modules
    Child extract-text-webpack-plugin:
           + 8 hidden modules

    marco@pc01:~/go/src/bee-gorm-graphql$ bee run #open http://localhost:8080
    ______
    | ___ \
    | |_/ /  ___   ___
    | ___ \ / _ \ / _ \
    | |_/ /|  __/|  __/
    \____/  \___| \___| v1.10.0
    2019/06/05 14:22:40 INFO     ▶ 0001 Using 'bee-gorm-graphql' as 'appname'
    2019/06/05 14:22:40 INFO     ▶ 0002 Initializing watcher...
    ../github.com/neelance/graphql-go/graphql.go:10:2: use of internal package github.com/graph-  
    gophers/graphql-go/internal/common not allowed
    ../github.com/neelance/graphql-go/graphql.go:11:2: use of internal package github.com/graph-
    gophers/graphql-go/internal/exec not allowed
    ../github.com/neelance/graphql-go/graphql.go:12:2: use of internal package github.com/graph-
    gophers/graphql-go/internal/exec/resolvable not allowed
    ../github.com/neelance/graphql-go/graphql.go:13:2: use of internal package github.com/graph-
    gophers/graphql-go/internal/exec/selected not allowed
    ../github.com/neelance/graphql-go/graphql.go:14:2: use of internal package github.com/graph-
    gophers/graphql-go/internal/query not allowed
    ../github.com/neelance/graphql-go/graphql.go:15:2: use of internal package github.com/graph-
    gophers/graphql-go/internal/schema not allowed
    ../github.com/neelance/graphql-go/graphql.go:16:2: use of internal package github.com/graph-
    gophers/graphql-go/internal/validation not allowed
    2019/06/05 14:22:40 ERROR    ▶ 0003 Failed to build the application: ../github.com/neelance
    /graphql-go/graphql.go:10:2: use of internal package github.com/graph-gophers/graphql-
    go/internal/common not allowed
    ../github.com/neelance/graphql-go/graphql.go:11:2: use of internal package github.com/graph-
    gophers/graphql-go/internal/exec not allowed
    ../github.com/neelance/graphql-go/graphql.go:12:2: use of internal package github.com/graph-
    gophers/graphql-go/internal/exec/resolvable not allowed
    ../github.com/neelance/graphql-go/graphql.go:13:2: use of internal package github.com/graph-
    gophers/graphql-go/internal/exec/selected not allowed
    ../github.com/neelance/graphql-go/graphql.go:14:2: use of internal package github.com/graph-
    gophers/graphql-go/internal/query not allowed
    ../github.com/neelance/graphql-go/graphql.go:15:2: use of internal package github.com/graph-
    gophers/graphql-go/internal/schema not allowed
    ../github.com/neelance/graphql-go/graphql.go:16:2: use of internal package github.com/graph-
    gophers/graphql-go/internal/validation not allowed

    go version go1.12.5 linux/amd64

How to solve the problem?
Marco

**Comment by pavelnikolov** [comment]
In Go you are not really allowed to use anything that lives in a package `internal` from packages that do not share the same root path. In other words it's private. If we allowed the use of this package it would mean that changes to it would be a lot more difficult. This code is for internal use only. We want to be able to change it without worrying about breaking changes. If you want a change in the public API then you can send a separate issue about it. Is there anything in particular that doesn't work for you?

**Comment by marcoippolito** [comment]
@pavelnikolov I do understand the reasons and the rationale behind to "internal package not allowed". but the question is: as "user" of bee-gorm-graphql package which gives this error message as output when trying to run the application, what can I do? And what should I tell the author of this package in order to solve the problem?

**Comment by bsr203** [comment]
@marcoippolito  also the imports in the error message points to a different/old package `github.com/neelance/graphql-go`. you may want to check with bee-gorm-graphql  package and use the `github.com/graph-gophers/graphql-go` import.
