### ISSUE TITLE
Versioning and fetching from go.mod

### ISSUE THREAD

**Issue by linuxmonk** [graph-gophers/graphql-go#344]
I see that the repository don't have any git tags semantically versioned. This wouldn't let me easily identify versions of the project and move between them. I'll have to rely on a specific git-hash which makes it a bit difficult to find out what has changed between commits. Would it be possible to add tags so that it can be referred from the go.mod file. Something like -

`
require (
        github.com/graph-gophers/graphql-go v1.0.1a
)
`

instead of something like -

`
require (
        github.com/graph-gophers/graphql-go v0.0.0-20190205233743-95e4a602e3fa
)
`

**Comment by asutosh97** [comment]
Hey, I would like to take up this issue.

**Comment by m3talsmith** [comment]
@asutosh97 take it away! 👍

**Comment by fabaff** [comment]
I'm with @linuxmonk on this.

This would with the distribution packages as well. For the Fedora RPM the versioning details looks very human-unfriendly: `0-0.1.20200702gitdae41bd.fc33`
