### ISSUE TITLE
Modifying Context within a Resolver

### ISSUE THREAD

**Issue by sjakati98** [graph-gophers/graphql-go#347]
Is there a way to access/modify the context object within a resolver. I am trying to load tokens to my context. Currently, I have something like:

```go
func (r *Resolver) Login(ctx context.Context, *args LoginArgs) (*UserResolver, error) {
        // logic to login and get user
        // ....
        accessToken, refreshToken := tokenutil.CreateTokensForUser(user)
        accessTokenString, refreshTokenString, err := tokenutil.SignTokens(accessToken, refreshToken)
	if err != nil {
		return nil, err
	}
	// replace existing tokens
	err = loadTokensToContext(&ctx, *accessTokenString, *refreshTokenString)
	if err != nil {
		return nil, err
	}
	//return user
	return &result, nil
}
```

Obviously I know that it is not really modifying the context object from the handler, but is there a way to do so? If not, does anyone have another solution to get the tokens in the response?

**Comment by zhaogaolong** [comment]
hi @sjakati98 
   In my practice ，in native http.request do it, get and set user token to request context
```go
router.Handle("/graphql", middleware.AuthRequired(http.HandlerFunc(graphql.GraphQL)))
```
add have token's context set to http.request, graphql Resolver get token in context. next start your  resource permission validation logic。
```go
func GraphQL(w http.ResponseWriter, r *http.Request) {
	var params struct {
		Query         string                 `json:"query"`
		OperationName string                 `json:"operationName"`
		Variables     map[string]interface{} `json:"variables"`
	}
	if err := json.NewDecoder(r.Body).Decode(&params); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	
	token := r.Context().Value(pkg.Token).(string)
	response, op := mySchema.Exec(r.Context(), params.Query, params.OperationName, params.Variables)
       ....

```



   I don't know you know my meaning or help you with your question.

**Comment by pavelnikolov** [comment]
This has nothing to do with this library. You can add values to the context just like in this example: https://golang.org/pkg/context/#example_WithValue
