### ISSUE TITLE
graphql: panic occurred: reflect: call of reflect.Value.Field on chan Value

### ISSUE THREAD

**Issue by SogoCZE** [graph-gophers/graphql-go#348]
Hello, 

I've noticed that when you try to use subscriptions with basic HTTP requests that do not include
a `graphql-ws` subprotocol it resolves that subscription with `schema.exec` which ends up using a subscriptions resolver that returns chan and causes reflection panic. 

So I thought it would be better to prevent this panic and return a reasonable error message in case of a subscription request without `graphql-ws` subprotocol.

I accomplished that by adding a simple if statement to the exec method.

```go
if op.Type == "SUBSCRIPTION" {
    return &Response{Errors: []*errors.QueryError{errors.Errorf("graphql-ws protocol header is missing")}}
}
```

I'm new to this library so I would like to ask if I missed something or it's a real problem and I should create pull-request?

**Comment by pavelnikolov** [comment]
Well, additional validation never hurts. PR with that validation + a unit test would be welcome.
