### ISSUE TITLE
Using sessions in resolver

### ISSUE THREAD

**Issue by t0nyandre** [graph-gophers/graphql-go#354]
I have been itching my head for days now trying to figure out how to properly use sessions inside resolver for authentication. Is it even possible?

**Comment by smitt04** [comment]
I would do all your authentication outside graphql and then set any values you want passed to your resolvers on the `context`.

Example:

**Comment by jmichalicek** [comment]
What @smitt04 suggested is how I have been doing it with my project. I have a middleware which handles the authentication and then adds the user to the context,

The general flow is:
* Auth via graphQL mutation - input takes username and password, returns data with token
* Middleware checks for token, validates, adds user to context
* Mutations and queries pull user out of context and do what they should, including handling no user.

I do need to put together a less repetitve version of step 3 there - would love something akin to a decorator in python or a way to specify a "before resolver function" hook in this framework type deal but I have not put much thought into that.

**Comment by pavelnikolov** [comment]
I'd check for `Authorization` header and pass the value of the user ID in the context. You can use any type of authentication - basic, JWT token, etc. This library should be authentication/sessions agnostic.
