### ISSUE TITLE
Question: Number of resolvers per request?

### ISSUE THREAD

**Issue by salman-bhai** [graph-gophers/graphql-go#368]
Hi, so we are using this library at work and were looking at a certain optimisation. 

> In graphql-go, the default limit of the maximum number of resolvers per request allowed to run in parallel was 10, which now is increased and passed as an option during the initialisation of schema. Performance improvements and other impacts has to be find out by load testing. 

We've increased maximum number of resolvers per request to 50 as of now. Quick question though, was there a specific reason why `graphql-go` limit was set to 10? Or was it a limit that was started off with and hasn't been experimented with?

Thank you again for creating an amazing library for people to work with.

https://github.com/graph-gophers/graphql-go/blob/master/graphql.go#L103

Referring to this specifically

**Comment by pavelnikolov** [comment]
I am not really sure why 10 was chosen. However, each and every application is unique so I'd expect requirements to be different. I am closing this as it is not a real issue and it gives you the ability to change it.
