### ISSUE TITLE
Limit Goroutines Spawned in execSelections

### ISSUE THREAD

**Issue by shannontan-bolt** [graph-gophers/graphql-go#375]
We recently ran into a problem with large amounts of go routines being spawned and overwhelming the memory of the machine leading to a shutdown. After receiving tens of thousands of records from the DB, they were converted into resolvers, and then execSelections was called. execSelections appears to spawn a go routine for each field within this list, which means that the amount of goroutines will be proportional to the amount of fields in the list.

However, the execution is limited within execSelectionSet by the size of the limiter channel - so there's only 10 goroutines allowed to execute at any point in time. Instead of creating the goroutines and limiting the execution of them, it would be preferable to just limit the amount of goroutines being created and letting them run.

I agree that we should be limiting the records we retrieve from the DB, but this should manifest as slowness rather than system instability.

There are a few proposed solutions:
- Add the ability to limit the amount of fields in `execList`. This would be a SchemaOpt + a check that would add a runtime error if the list of the fields is too large. This would prevent too many goroutines from being spawned.
- Refactor the code (likely a significant refactor) such that each execSelectionSet/execSelection is run in a separate goroutine thereby allowing the parent goroutine to complete. This would require introducing something else to manage state since children goroutines would no longer be able to just update a local variable within the parent goroutine.
- This is very similar to the above idea, but with another change to make it breadth first: https://github.com/graph-gophers/graphql-go/pull/372/files

**Comment by amzuko** [comment]
We have encountered this problem as well, when returning a substantial set of structured data in a single query. We are also interested in finding ways to control the number of goroutines spawned.

**Comment by keegancsmith** [comment]
At Sourcegraph this has been a problem for us as well. We implemented a small change which helps to bound the number of goroutines, and it is working well for us. https://github.com/graph-gophers/graphql-go/pull/400

**Comment by pavelnikolov** [comment]
Closing this issue since #400 takes care of it.
