### ISSUE TITLE
Detailed Panic Logging along with operation name, query string and variables

### ISSUE THREAD

**Issue by abhif22** [graph-gophers/graphql-go#383]
Detailed Panic Logging along with queryString and variables

Hi,
Although we have the full stack trace during the panic, it is nearly impossible to trace back the exact query and variables which caused the panic sometimes. For instance in below cases:

```
panic occurred: graphql: could not marshal -Inf: json: unsupported value: -Inf
goroutine 296550 [running]:
github.com/graphqlDemoApp/vendor/github.com/graph-gophers/graphql-go/log.(*DefaultLogger).LogPanic(0xc123ab28c0, 0xc123ab28c0, 0xc123ab28c0, 0xc123ab28c0, 0xc123ab28c0)
	/share/dpkg-build/graphqlDemoApp-build/src/github.com/graphqlDemoApp/vendor/github.com/graph-gophers/graphql-go/log/log.go:21 +0xc123ab28c0
github.com/graphqlDemoApp/vendor/github.com/graph-gophers/graphql-go/internal/exec.(*Request).handlePanic(0xc123ab28c0, 0xc123ab28c0, 0xc123ab28c0)
	/share/dpkg-build/graphqlDemoApp-build/src/github.com/graphqlDemoApp/vendor/github.com/graph-gophers/graphql-go/internal/exec/exec.go:31 +0xc123ab28c0
panic(0xc123ab28c0, 0xc123ab28c0)
	/usr/local/go/src/runtime/panic.go:502 +0xc123ab28c0
github.com/graphqlDemoApp/vendor/github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelectionSet(0xc123ab28c0, 0xc123ab28c0, 0xc123ab28c0, 0xc123ab28c0, 0xc123ab28c0, 0xc123ab28c0, 0xc123ab28c0, 0xc123ab28c0, 0xc123ab28c0, 0xc123ab28c0, ...)
	/share/dpkg-build/graphqlDemoApp-build/src/github.com/graphqlDemoApp/vendor/github.com/graph-gophers/graphql-go/internal/exec/exec.go:284 +0xc123ab28c0
github.com/graphqlDemoApp/vendor/github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection(0xc123ab28c0, 0xc123ab28c0, 0xc123ab28c0, 0xc123ab28c0, 0xc123ab28c0, 0xc123ab28c0, 0xc123ab28c0)
	/share/dpkg-build/graphqlDemoApp-build/src/github.com/graphqlDemoApp/vendor/github.com/graph-gophers/graphql-go/internal/exec/exec.go:243 +0xc123ab28c0
github.com/graphqlDemoApp/vendor/github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelections(0xc123ab28c0, 0xc123ab28c0, 0xc123ab28c0, 0xc123ab28c0, 0xc123ab28c0, 0xc123ab28c0, 0xc123ab28c0, 0xc123ab28c0, 0xc123ab28c0, 0xc123ab28c0, ...)
	
```

In production systems a request can originate from app(ios/android) or desktop and over months the number of queries keep growing in number and thus it becomes very tedious to pin-point the root problem. We can leverage the information like queryString, operationName and variables available to us in `exec` method on Schema to add more details when logging the panic and stack trace.

Besides, if any application sets useful keys like `device info and app versions` on the context, it can also be used for logging and provide good insights on the origin of the problem.

**Comment by pavelnikolov** [comment]
I usually log the trace ID in every log message, then if I am lucky enough that the request tracing info had been sampled I can open it. Also, if the issue is reproducible I run the same request with forced sampling then I inspect the request trace for a fast root cause analysis.
If on the other hand, it is a one-off error, then I don't spend too much time on it. I agree with you that logging can be improved.

I agree with you that better panic logging would be ideal. PRs are welcome.

**Comment by pavelnikolov** [comment]
After thinking about this, maybe it could be better to add your own logging middleware without adding any specific code to the library. This way the users can override the default behaviour as they see fit.

**Comment by abhif22** [comment]
Apology for delayed reply. 
Since `panic` logging can be/already handled only from inside the handlePanic method, I think it would be a really good idea to create a verbose logger which extends `log.Logger` interface. We can then expose a new `SchemaOpt` function from graphql.go which will set logging to the verbose instead of the default logging.

I have created a change, you may wanna review it  -> https://github.com/graph-gophers/graphql-go/pull/384

**Comment by pavelnikolov** [comment]
this can be found using tracing provided that you log the traceID as well
