### ISSUE TITLE
Authorization best practices

### ISSUE THREAD

**Issue by muety** [graph-gophers/graphql-go#385]
Hi! First of all, thanks a lot for this project. It's such an easy way to do GraphQL in Go. 

However, the only thing that I'm kind of missing is authorization. I'd like to restrict not only access to the GraphQL endpoint itself, but also restrict certain queries and mutations, depending on a user's rights. For instance, I potentially don't want a user to execute a query to list all other users, while an admin, in turn, should be able to do so. 

I though of integrating these checks as traditional authorization middleware that executes before the GraphQL handler itself. But at that point I don't have a parsed query, yet. 

Can somebody give some best practices regarding auth. here? Thanks a lot!

**Comment by pavelnikolov** [comment]
Hi, @muety! As you have mentioned the best way to do it is to wrap the GraphQL handler with your authentication middleware. This way you can add information about each user in the request's context. Then at the resolver level you can extract the user and based on a role/access policy you can allow the action or throw error. How you implement this is up to you. My recommendation would be to use the context which is propagated through the resolvers out of the box with this library. Then the authorization is BYO.

ATM this is entirely imperative. One day, when there is a better support for directives you might be able to write a middleware that solves this problem declaratively. I am closing this issue for now as authorization is outside of the scope of this library for now. The library remains agnostic as to how you manage authorization in your application.
