### ISSUE TITLE
String literals for description

### ISSUE THREAD

**Issue by rinatio** [graph-gophers/graphql-go#387]
Seems like it's not possible to use `"""` or `"` to make some description in graphql schema. It returns an error:

```
panic: graphql: syntax error: unexpected "\"\"", expecting Ident
```

**Comment by pavelnikolov** [comment]
It is possible. However, this feature was introduced later and this is why it is opt-in in this library to avoid breaking changes. In order to use it you have to use a [special schema option](https://github.com/graph-gophers/graphql-go/blob/a5bf8047ea0532f7a93369db63130adbb739a65d/graphql.go#L83):

```go
opts := []graphql.SchemaOpt{graphql.UseStringDescriptions()}
schema := graphql.MustParseSchema(s, &query{}, opts...)
```
