### ISSUE TITLE
undefined: graphql.UseFieldRootResolvers with go mod

### ISSUE THREAD

**Issue by flofeld** [graph-gophers/graphql-go#395]
After turning my project into a module, graphql.UseFieldRootResolvers is undefined. 
I am quite new to modules, so any common mistake I could have made?

Import:
```
graphql "github.com/graph-gophers/graphql-go"
"github.com/graph-gophers/graphql-go/relay"
```

go.mod
`github.com/graph-gophers/graphql-go v0.0.0-20200309224638-dae41bde9ef9`

**Comment by smithaitufe** [comment]
@flofeld 

Please where did you find this graphql.UseFieldRootResolvers?

**Comment by dackroyd** [comment]
`graphql.UseFieldRootResolvers` I assume is actually meant to be `graphql.UseFieldResolvers`? https://github.com/graph-gophers/graphql-go/blob/master/graphql.go#L89:L94
