### ISSUE TITLE
How to define structs for input types with optional fields?

### ISSUE THREAD

**Issue by MrCreeper1008** [graph-gophers/graphql-go#397]
I am trying to write a resolver for this mutation:
```graphql
type Mutation {
  register(input: UserInput!): User!
}

input UserInput {
  username: String!
  email: String!
  avatar: String
}
```
the resolver look like this:
```go
type RegisterInput struct {
    Input struct {
        Username string
        Email string
        Avatar string
    }
}

func (*Resolvers) Register(ctx context.Context, args RegisterInput) (*user.userResolver, error) {
  // logic here
}
```
When I compile my code, I get an error saying `avatar` string is not a pointer, which I guess is due to it being optional and can take in a null pointer. So I switch the field types into `*string`:
```
Username *string
Email *string
Avatar *string
```
The code can compile just fine after this, but when i try to call the mutation, I get an error saying "cannot unmarshal string into *string". I tried to write a resolver for `UserInput`, but it seems to not be able to recognize resolver funcs as fields. How do I solve this? Thank you!

**Comment by tonyghita** [comment]
From your definition it looks like only `avatar` is defined as `String`, whereas `username` and `email` are defined as `String!`.

You can think of the GraphQL to Go type mappings as:
- `String  => *string`, since it can be `null` (`nil` in Go)
- `String! => string`, since it must always be a string value (empty string `""` is a string value).

So, it seems like you want something like
```go
type UserInput struct {
  Avatar   *string
  Email    string
  Username string
}

type RegisterArgs struct {
  Input UserInput
}

func (*Resolvers) Register(ctx context.Context, args RegisterArgs) (*user.userResolver, error) {
  // logic here
}
```

**Comment by MrCreeper1008** [comment]
Why didn't I think of that? Thank you so much it worked like a charm!
