### ISSUE TITLE
Is it possible to have a "catch-all" resolver?

### ISSUE THREAD

**Issue by ayvazj** [graph-gophers/graphql-go#427]
> A resolver must have one method or field for each field of the GraphQL type it resolves

I am building a proxy service where I want to handle a subset of GrapQL queries and I do not want to implement a method for each field.  Is there a way to define a catch all or default resolver to handle fields or methods that are not implemented in the resolver.  Thanks.

**Comment by pavelnikolov** [comment]
No, I'm sorry but the library doesn't offer that.
