### ISSUE TITLE
No child data available in response when parent is null

### ISSUE THREAD

**Issue by ruanspies-rezco** [graph-gophers/graphql-go#435]
I am facing problems with nullable fields when trying to use the data returned when executing my query. 

**Schema**
A simplified schema for demonstration purpose:

```
type Query {
    members: [Instrument!]!
}

type Instrument {
    series: SeriesType!
    ...
}

type SeriesType {
    dividendYield: SeriesMethods
    ...
}

type SeriesMethods{
    latest: Float!
    ...
}
```

There is nullable data that is resolved at dividendYield and a typical response I get when executing the query is shown in the following section.

**Typical Response**

<img width="544" alt="Screenshot 2021-02-26 at 10 56 49" src="https://user-images.githubusercontent.com/69503530/109279717-c25c9280-7822-11eb-8f79-ca2cfe75671d.png">

**So what is the problem???**

We are using this data to for visuals on a web app. The data is read in as an object such that you are able to access the data by `data.series.dividendYield.latest`. The problem comes in when dividendYield returns null as there is there no longer exists a _latest_ field anymore. 

For the client side it will always be necessary for the field to be present in the data, even if the parent resolver is null. Is it possible for the resolvers to be setup such that all children fields also return null rather than not appearing in the data response? Any other solutions would also be appreciated.

**Comment by ssko1** [comment]
Hey @ruanspies-rezco, 

Have you tried setting the field `dividendYield` to required?
```graphql
type SeriesType {
    dividendYield: SeriesMethods!
    ...
}
```

If your back-end somehow produces a value that would yield `null`, you could replace it with an object that has zero-values. Default values could also work if it fits your use case.

Does this suggestion help?

**Comment by ruanspies-rezco** [comment]
Thanks for the response @ssko1. Yes, that is the way we set it up initially but it results an inefficient backend. Our schema is quite complex and resolves larges amounts of data so the execution of graphql is ideal in that it does not unnecessarily try fetch child data if the parent is null. eg. if `dividendYield` is null then I do not want to execute any of the child resolvers.

From the client side, I do however want to know that if I queried _latest_ that it is null rather than completely missing from the response.

**Comment by ssko1** [comment]
I don't really have a clear picture of *where* the inefficiencies come into play. Could you say more to this?

Which part of your schema is the most expensive in terms of compute resources? 

Are you running into the case where GraphQL, upon receiving a null value for a required field, propagates the error and returns the first nullable field (in this case: `dividendYield`)? If you are running into this issue, you could make `latest: Float!` a nullable field `latest: Float`, but it's hard to say given that there are nuances in your back-end to consider.

**Comment by pavelnikolov** [comment]
@ruanspies-rezco I am closing this issue as it sounds that it is a problem with your schema rather than the library itself. @ssko1 is right that you need a non-nullable field if you want to always have its children available.
