### ISSUE TITLE
Option to disable verbose schema validation errors

### ISSUE THREAD

**Issue by rinatio** [graph-gophers/graphql-go#448]
Hello! We're looking for an option to disable verbose error messages when request validation or unmarshaling fails because it might potentially give some insights for malicious users. Is there some option that we can use to return a general `invalid request` message for example or what would be the best way to change the default behavior?

**Comment by pavelnikolov** [comment]
The option you are looking for doesn't exist yet. As an immediate workaround, with a little performance degradation, you can handle this outside of the library, just before you return the response - in case of an error you can just return a generic message. PRs are more than welcome, just make sure that this is a backwards compatible, opt-in change.

**Comment by rinatio** [comment]
Thank you, Pavel!

Is there a way to identify if it's a GraphQL syntax error or something else because we'd like to disable only syntax error messages and keep the others? Where is the place it needs to be handled if it's not a workaround - should it be a custom ValidationTracer?

Can we support this feature development through Patreon or some other platform?

**Comment by rinatio** [comment]
@pavelnikolov I followed your advice and handled that outside of the library. Checking if the `ResolverError` on the `QueryError` is presented in the `response.Errors` list helped to figure out if a particular error is internal or not. Thank you for the hint!
