### ISSUE TITLE
expose Unmarshaler interface

### ISSUE THREAD

**Issue by sGy1980de** [graph-gophers/graphql-go#449]
Hey guys,

I was wondering why there seems to be no interface for the `Unmarshaler` type. 
Turns out there is one, but it's hidden in the `internal` scope.

This makes it impossible to have an assertion, whether my own type implements it properly or not.
So is there a particular reason, why it is internal or is it by mistake?

**Comment by maoueh** [comment]
@sGy1980de As a workaround, you can always define the same interface in your own code and test against, this works also in  Go, you don't need to check against the actual defined interface.

```
package main

import (
  "fmt"
)

type I interface {
  Stringify() string
}

type S1 struct {
  value string
}

func (s *S1) Stringify() string {
  return s.value
}

type randomI interface {
  Stringify() string
}

func main() {
   s1 := &S1{}
   var v interface{} = s1
   
   _, isI := v.(I)
   _, isRandomI := v.(randomI)
   
   fmt.Println("Answers", isI, isRandomI)
}
```

See https://play.golang.org/p/iAepjwPZL8k

You can use it to make your check on your side.
