### ISSUE TITLE
Capture original error in errors.QueryError to preserve information for trace.Tracer implementations

### ISSUE THREAD

**Issue by savaki** [graph-gophers/graphql-go#455]
Would you accept a change to allow errors.QueryError to store the original error that an operation returned?  This would preserve the data potentially contained in the original error for the Tracer implementation.  I believe this could be implemented with minimal disruption, potentially as simple as:

1. modifying `errors.Errorf` to store the error if present as the last argument.  So calls like `r.AddError(errors.Errorf("%s", err))` shouldn't require any modifications.
2. expose an `Unwrap` method on `errors.QueryError` to conform to Go's error handling
3. optionally expose the underlying `error` directly seeing as most of the time, developers will be directly manipulating instances of `errors.QueryError`

Thoughts?

**Comment by pavelnikolov** [comment]
Yes, PR is welcome
