### ISSUE TITLE
Batch Resolving

### ISSUE THREAD

**Issue by steve-gray** [graph-gophers/graphql-go#458]
Is there a way to be able to have multiple entities/traversals get resolved using a single call?

Been checking for issues that relate to this, but I can't find one - there's one where I **think** the person had the same idea, but it got lost in another discussion. https://github.com/graph-gophers/graphql-go/issues/263

Example scenario:
```
{
    query {
          Country { 
              Name
              County {
                   Name
              }
          }
     }
}
```

In this example, the resolver picks up the list of countries, but then in parallel does independent calls one by one to resolve the counties - what would be ideal is that if I could specify an alternate method syntax that takes a slice/vector of ID's and performs a batched fetch from the target service, de-duplicating equivalent identities (i.e. if you're referencing the same object 10 times in 1000 children, it'd only put that object in once to the resolver). Then if I have to resolve the list of counties per country, it does either:

- One call that does all the sub-fetches (if my "Max Batch Size" is high enough)
- N batched requests, if my batch size is less than the number of items to do (so for example, fetch in blocks of 10, 20)
- One by one, if no batch signature function exists for this resolver.

Is this something present in the framework, or something roadmapped?

**Comment by pavelnikolov** [comment]
You might be interested in the data-loader repository under this same project.

**Comment by pavelnikolov** [comment]
Check out the dataloader repo: https://github.com/graph-gophers/dataloader
