### ISSUE TITLE
Yours examples not working

### ISSUE THREAD

**Issue by IgorDePaula** [graph-gophers/graphql-go#459]
I restarted the IDE but nothing resolves.
![Captura de tela de 2021-06-05 15-35-15](https://user-images.githubusercontent.com/2833993/120901917-e0047980-c613-11eb-95b5-4c791ae6dee1.png)
![Captura de tela de 2021-06-05 15-37-18](https://user-images.githubusercontent.com/2833993/120901936-ee529580-c613-11eb-9070-30c2de1a110b.png)

**Comment by pavelnikolov** [comment]
I just tried in the terminal. It definitely works for me. Both the library and the examples. I tried both the latest commit and v1.1.0. The issue must be with your IDE or environment. I built it locally with `go version go1.16.2 darwin/amd64`.
<img width="431" alt="Screen Shot 2021-06-07 at 3 12 39 pm" src="https://user-images.githubusercontent.com/441740/121014641-de1cf080-c7a2-11eb-8334-883c909c220b.png">
