### ISSUE TITLE
How to create custom scalar type Map?

### ISSUE THREAD

**Issue by GustavoDelfim** [graph-gophers/graphql-go#464]
Can I create a scalar type Map? Because I have a request that receive a field type []map[string]interface{}
Reference: https://github.com/graph-gophers/graphql-go/issues/252

I didn't understand where I create the code:
```
type Map map[string]interface{}
func (Map) ImplementsGraphQLType(name string) bool { return name == "Map" }
func (j *Map) UnmarshalGraphQL(input interface{}) error {
	switch input := input.(type) {
	case Map:
		*j = input
		return nil
	default:
		return fmt.Errorf("wrong type")
	}
}
```

Help me please, Thank you

**Comment by pavelnikolov** [comment]
You need to create a custom struct of whatever type you want to create as explained in that issue. Then your struct needs to implement two methods `ImplementsGraphQLType` and `UnmarshalGraphQL`. This will allow you to use the struct as a field type in your resolvers.

**Comment by GustavoDelfim** [comment]
Thank you, I implemented this way, but now I am receiving this error when I try to do a request
`Argument \"dados\" has invalid value [{param: \"Valor\"}].\nIn element #0: Expected type \"Map\", found {param: \"Valor\"}`

My schema:

```
scalar Map

type AdicionaRelatorioType {
  id: String!
  nome: String!
  codigo: Int!
  id_empresa: Int!
  criado_em: String!
  alterado_em: String!
  dados: [Map!]!
}

type Mutation {
  adicionaRelatorio (
    codigo: Int!
    nome: String!
    dados: [Map!]!
  ): AdicionaRelatorioType!
}
```

In My resolver:
```
type Args struct {
	Codigo int32 `json:"codigo"`
	Nome string `json:"nome"`
	Dados []types.Map `json:"dados"`
}

type Response struct {
  Args
  Id string `json:"id"`
  Id_empresa int32 `json:"id_empresa"`
  Criado_em string `json:"criado_em"`
  Alterado_em string `json:"alterado_em"`
}
```


my Resquest:
```
mutation {
  adicionaRelatorio(
    codigo: 26, 
    nome: "MENSAL_FORMA_PAGTO"
    dados: [{ param: "Valor" }]
  ) {
    id
  }
}
```

end Map is the code above

There is a problem that I can't change the request, because the request is like this currently and the parameter "data" will always be in different ways.
Is There  the way to resolver this without I need to separate the dados's values to "variables"? as this comments shows https://github.com/graph-gophers/graphql-go/issues/350#issuecomment-530485923
