### ISSUE TITLE
Misleading changelog for tag v1.2.0

### ISSUE THREAD

**Issue by sGy1980de** [graph-gophers/graphql-go#469]
Hey guys,

I was really excited when I saw the first bullet point in the [changelog for release v1.2.0](https://github.com/graph-gophers/graphql-go/releases/tag/v1.2.0), because I waited for this feature to come for quite some time now. Turns out, the linked issue #428 has only been closed but not merged and the feature isn't there at all, neither via dedicated argument nor via context. 

Could we please just pick one approach or start a community vote which route they want to pick? It would really ease up some of our schemas and loaders if we would have this information upfront.

Please this discussion is going on for years now.

**Comment by pavelnikolov** [comment]
Hi @sGy1980de 

Thank you for reporting this. It was my mistake 🤦‍♂️ I'll try to merge the proper change and will fix it this weekend. My intention was to add this feature.

**Comment by sGy1980de** [comment]
Hey @pavelnikolov,

happy to hear this. Really looking forward to this and let me thank for the precious work you guys do here.

Bye

**Comment by pavelnikolov** [comment]
I've removed the misleading feature. I'll add it with the next release soon. Thank you for reporting.
