### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by SCKelemen** [graph-gophers/graphql-go#47]
Is there any documentation or guide for resolvers? The starwars example seems pretty convoluted.

**Comment by tonyghita** [comment]
Can you be a little more specific on what is confusing to you about the example given? I could take a shot at writing an example based off of an approach I've taken, but it would help to know which points are most unclear.

**Comment by SCKelemen** [comment]
I just need to see how mutations work. How to expose the mutation over the graphql api and then how to make a function, like with anonymous functions/lambda expressions, or calling a method.

**Comment by EmperorEarth** [comment]
I'm figuring it out as I go but I'll contribute 1-2 examples to this repo in the next 2 months, with persistence and authentication+authorization. (I have those things working right now, but want some time to my implementations have gaps)

For now, this is what I've been doing:

`schema.graphql`
```
type Schema {
	query: Query
	mutation: Mutation
}
type Query {
	foo(id: ID!): Foo
}
type Mutation {
	createFoo(bar: String!, baz: String): Foo
}
type Foo {
	id: ID!
	bar: String!
	baz: String
}
```

`main.go`
```
func main() {
	db, _ db.Open("...")
	rawSchema, _ := ioutil.ReadFile("/path/to/schema.graphql")
	parsedSchema, _ := graphql.ParseSchema(string(rawSchema), NewResolver(db))
	if os.Getenv("production") != "true" {
		http.HandleFunc("/", graphiqlHandler)
	}
	http.Handle("/graphql", Middleware(injectViewerToContext(&relay.Handler{Schema: parsedSchema})))
	http.ListenAndServe(":8080", nil)
}

func injectViewerToContext(next http.Handler) http.Handler {
	return func(w http.ResponseWriter, r *http.Request) {
		viewerID, _ := authenticate(r.Header.Get("Authorization")) // your custom 401 function
		next.ServeHTTP(w, r.WithContext(context.WithValue(r.Context(), "Authorization", viewerID))) // pass a custom viewer type with roles, etc
	}
}
```

`resolver.go`
```
type Resolver { db: *sql.DB }
func NewResolver(db *sql.DB) *Resolver {
	return &Resolver{db: db}
}

func (r *Resolver) Foo(ctx context.Context, args *struct{ ID string }) (*FooResolver, error) {
	viewerID, _ := context.Value("auth", ctx).(uuid.UUID)
	return NewFooResolver(viewerID, args.ID, r.db)
}

func (r *Resolver) CreateFoo(ctx context.Context, args *struct{
	Bar	string
	Baz	*string
} (*FooResolver, error) {
	viewerID, _ := context.Value("auth", ctx).(uuid.UUID)
	id, _ := NewFoo(viewerID, args.Bar, args.Baz, r.db)
	return NewFooResolver(viewerID, id, r.db)
}
```

`foo.go`
```
func NewFoo(viewerID uuid.UUID, bar string, bazPtr *string, db *sql.DB) (uuid.UUID, error) {
	var mtID uuid.UUID

	// do some 403
	if !mayCreateFoo(viewerID) {
		return mtID, errors.New("403")
	}

	id := uuid.NewV1()
	tx, _ := db.Begin()
	_, _ = tx.Exec("INSERT INTO foo_bar (id, bar) VALUES ('%s', '%s')", id.Bytes(), args.Bar)
	if bazPtr != nil {
		_, _ = tx.Exec("INSERT INTO foo_baz (id, baz) VALUES ('%s', '%s')", id.Bytes(), *args.Baz)
	}
	_ = tx.Commit()
	return NewFooResolver(viewerID, id, db), nil
}

type FooResolver struct {
	viewerID	uuid.UUID
	id		uuid.UUID
	db		*sql.DB
}

func NewFooResolver(viewerID, id uuid.UUID, db *sql.DB) (*FooResolver, error) {
	return &FooResolver{
		viewerID: viewerID,
		id: id,
		db: db,
	}, nil
}

func (r *FooResolver) ID() string {
	return r.id.String()
}

func (r *FooResolver) Bar() (string, error) {
	// do some 403
	if !mayViewBar() {
		return "", errors.New("403")
	}

	var bar string
	_ := r.db.QueryRow("SELECT bar FROM foo_bar WHERE id='%s'", r.id.Bytes()).Scan(&bar)
	return bar, nil
}

func (r *FooResolver) Baz) (*string, error) {
	// do some 403
	if !mayViewBaz() {
		return "", errors.New("403")
	}

	var baz string
	_ := r.db.QueryRow("SELECT baz FROM foo_baz WHERE id='%s'", r.id.Bytes()).Scan(&baz)
	return &baz, nil
}
```

**Comment by SeerUK** [comment]
One other thing I've noticed while poking around the code is that there aren't many comments in general, but there something that could be useful in general would be godoc comments. I'd like to be able to contribute to the code if possible, but it makes it that much more difficult to start without any docs or comments.

**Comment by tsauvajon** [comment]
I'd be happy to contribute to a documentation, especially if there were a clear governance and guidelines !

I found it relatively hard to get started, even though the starwars example aswell as [this repo](https://github.com/tonyghita/graphql-go-example) helped a lot.

**Comment by tonyghita** [comment]
I've been working on a closer-to-real-life example that you may find helpful: https://github.com/tonyghita/graphql-go-example

It just wraps the API at https://swapi.co and implements some patterns I've found useful in my year of experience working with GraphQL+Go.

**Comment by tsauvajon** [comment]
@tonyghita well that's the repo I linked in my previous message!
Thanks it indeed helped a lot, I greatly inspired from your work!

**Comment by abradley2** [comment]
I've been looking at all the examples trying to implement whatever I can but I'm getting errors saying all fields in args need to be pointers. Has this changed?

**Comment by SCKelemen** [comment]
@tendolukwago I actually haven't. I haven't been working with GraphQL lately. I've mostly switched to gRPC. I've had less issues, and the documentation is better. (It's slightly different, though) I may be revisiting this in a few months, depending on how my priorities are set, by my team.
