### ISSUE TITLE
defer/stream support

### ISSUE THREAD

**Issue by agnivade** [graph-gophers/graphql-go#476]
I am creating this issue to start a discussion on implementing `@defer`/`@stream` support. Doing a search for existing issues, I could only find https://github.com/graph-gophers/graphql-go/issues/15 but that's only about subscriptions.

I have a use-case where my clients require `@stream` support to stream large payloads. I can go ahead and take a stab at implementing this, but I wanted to check if there has been any prior discussion around this and if anybody has any thoughts/comments on what things to consider?

Attaching the spec here: https://github.com/graphql/graphql-wg/blob/main/rfcs/DeferStream.md

cc @tonyghita @pavelnikolov

**Comment by pavelnikolov** [comment]
@agnivade I am not aware of anyone working on this. Considering that it's still a draft maybe we need to mention in the release later that  this feature will be experimental. As long as it's opt-in and it doesn't introduce any breaking changes - go for it.

**Comment by agnivade** [comment]
Yep, it's a directive on the client side, so totally opt-in. Thanks, I'll make an attempt soon.

**Comment by agnivade** [comment]
Sounds good. And my apologies for the delay. There has been some changes in company roadmap unfortunately which is not allowing me to invest more time in this.
