### ISSUE TITLE
Separate endpoint for subscriptions

### ISSUE THREAD

**Issue by pocockn** [graph-gophers/graphql-go#484]
I can't see this anywhere in the examples. Is it possible to have a separate subscriptions endpoint alongside the usually `graphql` one?

With my current setup below, I'm not sure it's possible to add subscriptions to my normal `graphql` endpoint

```
// GraphQL struct handles GraphQL API request over HTTP.
type GraphQL struct {
	handler          *relay.Handler
}

// NewGraphQL creates a new GraphQL handler.
func NewGraphQL(s *graphql.Schema, ll loader.Map, c *config.Config) *GraphQL {
	return &GraphQL{
		handler: &relay.Handler{
			Schema: s,
		},
	}
}

```

Within my `main.go`

```
s = graphql.MustParseSchema(schema.String(), r)

h := handler.NewGraphQL(s)

router.Handle("/graphql", logging.LoggingHandler(h))
```

Thanks

**Comment by pavelnikolov** [comment]
You don't need a separate endpoint to handle subscriptions. Your code will already handle subscriptions just fine.

**Comment by pavelnikolov** [comment]
https://github.com/graph-gophers/graphql-transport-ws
