### ISSUE TITLE
[Discuss] DDD Module Structure

### ISSUE THREAD

**Issue by sazzer** [graph-gophers/graphql-go#485]
Hi there,

I've just come across this module and have been playing, but am curious if there are any standard strategies/guidelines for module structure, and in particular in a project built around DDD guidelines.

Specifically, I'm wanting to have a number of subdomains that are entirely self-contained. Which means that under these subdomains are adapters that contain the schema, resolvers, model types and so on.

For example, take the following module structure:
```
- domains
  - users
    - adapters
      - primary
        - graphql
      - secondary
        - database
    - application
    - domain
  - posts
    - adapters
      - primary
        - graphql
      - secondary
        - database
    - application
    - domain
  - comments
    - adapters
      - primary
        - graphql
      - secondary
        - database
    - application
    - domain
```

Where each of the `domains/*/adapters/primary/graphql` packages contains the sub-schema and resolvers for that subdomain.

That in itself is relatively easy - right up until you have subdomains that refer to each other. At that point things get a bit circular and stop working correctly.

For example, if the schema ends up being (in part)
```
# Users subdomain
type User {
  posts: [Post]
}

# Posts subdomain
type Post {
  author: User
}
```

Then this ends up meaning that `domains/users/adapters/primary/graphql/userResolver` needs to return a reference to `domains/posts/adapters/primary/graphql/postResolver`, which itself needs to return a reference to `domains/users/adapters/primary/graphql/userResolver` - and that's not allowed.

Obviously, I can put all of the GraphQL resolvers in the same module, but that defeats the idea of splitting up subdomains. However, with the resolvers split into different modules, the best I've been able to come up with is to make the graph itself acyclic - e.g. have the `author` field of `Post` return an `ID` instead of a `User`, and then force the client to make another query to get user details. That also defeats the point of using GraphQL in the first place.

I know that in the Node version you get away with this because circular references *are* allowed. But is there some way to achieve this in Go as well?

Cheers

**Comment by pavelnikolov** [comment]
It looks like you need [GraphQL federation](https://www.apollographql.com/docs/federation/#federated-schemas), which is not supported by this library yet.

**Comment by sazzer** [comment]
Is federation not used to combine schemas from multiple *different* services? (That's what the term typically means, but I've not come across it in GraphQL until now)

I was wanting to do this purely from the point of view of the internal architecture of a single service. i.e. to split the code down business lines and not technical ones.

**Comment by pavelnikolov** [comment]
Oh, then what I usually do, and I know that several users of this library have done so too, is to split the services by domain as you've suggested. Then each service exposes some API through gRPC in my case (but you can use any protocol/technology you want). After that, the GraphQL server does not contain any business logic whatsoever and each resolver only returns data that it fetches through one of the many gRPC services.
