### ISSUE TITLE
Add an example of using graphql.ID

### ISSUE THREAD

**Issue by pavelnikolov** [graph-gophers/graphql-go#490]
Add an example of using graphql.ID. More specifically creating one from an integer and extracting an int value out of it. 
There should be an executable example in the main package and in the relay package.

**Comment by ConnieJChi** [comment]
👋 Hello!

Do you mind if take this issue? Thanks!

**Comment by ConnieJChi** [comment]
A quick question on the ask for this issue.
Looking at the GraphQL spec, it mentions that IDs should always be serialized to a string (http://spec.graphql.org/October2016/#sec-ID). In that case, should we provide examples of how to convert a GraphQL ID to an Integer if the specs recommend converting it to a String? I'd love to get more clarification on this. Thanks!

**Comment by pavelnikolov** [comment]
@ConnieJChi Feel free to add an executable example in `example_test.go` file in the `relay` package. Make sure that you use the `MarshalID`, `UnmarshalKind` and `UnmarshalSpec` in your executable examples.
