### ISSUE TITLE
Any plans to support enisdenjo/graphql-ws?

### ISSUE THREAD

**Issue by gerarts** [graph-gophers/graphql-go#501]
The current subscription example implements Apollo's [Apollo@v0.9.4 protocol](https://github.com/apollographql/subscriptions-transport-ws/blob/v0.9.4/PROTOCOL.md) but this protocol is no longer being maintained:

From the README in [apollographql/subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws#graphql-ws):
> The subscriptions-transport-ws library is not actively maintained. It is recommended that you use the [graphql-ws](https://github.com/enisdenjo/graphql-ws) library instead.

Are there any plans to add support for the [enisdenjo/graphql-ws](https://github.com/enisdenjo/graphql-ws) subscription protocol?

**Comment by pavelnikolov** [comment]
Hi @gerarts 
This was just a reference implementation and it is not production ready. The graph-gophers/graphql-go library is protocol agnostic as it works with Golang channels.
With that being said, we would be moving towards `graphql-ws` support but it is not an immediate priority. PRs are more than welcome.

**Comment by shkim** [comment]
With graphql-ws, I could not connect to go graphql server (different protocol?)
With subscriptions-transport-ws, I could not use vite, since subscriptions-transport-ws does not support ESM build.
There is some rollup config to use subscriptions-transport-ws in client build, but if I use vite SSR, it is not effective.

**Comment by pavelnikolov** [comment]
I'm closing this issue as the library is agnostic to protocols. It returns a Golang channel and you can use it with any protocol you want. We might add a reference implementation of the graphql-ws protocol in future but it is now in our immediate roadmap. PRs with a working example would be more than welcome.
