### ISSUE TITLE
Return an error if a schema has repeated directives without the repeatable keyword

### ISSUE THREAD

**Issue by pavelnikolov** [graph-gophers/graphql-go#509]
It was reported in https://github.com/graph-gophers/graphql-go/pull/502 that this library doesn't enforce uniqueness of non-repeatable directives. This is a bug and such a restriction needs to be enforced unless the `repeatable` keyword is present in the directive definition.

For example, if we are given two directives:

```
directive @repeatabledirective repeatable on SCALAR
directive @otherdirective on SCALAR
```
Then only the first one (i.e. `@repeatabledirective`) can be repeated multiple times on the same scalar type. If we repeat the `@otherdirective` more than once, then that should result in an error.

The issue is considered resolved when only directives declared as repeatable can be repeated.

**Comment by ostrea** [comment]
Good day. I would like to work on it. As far as I understand I need to update [this function](https://github.com/graph-gophers/graphql-go/blob/5a1c1721f1b3d0c600222327f4a6d1dd5dd1d50c/internal/schema/schema.go#L291) to return an error in case we see non `repeatable` directive for a second time. Is it correct?

**Comment by pavelnikolov** [comment]
@ostrea go for it!
