### ISSUE TITLE
Integer parsed as float64 when passed in as a variable

### ISSUE THREAD

**Issue by s1na** [graph-gophers/graphql-go#514]
Hi. We have a simple custom scalar `Long` which represents a int64 number. I.e.:

```go
type Long int64

// UnmarshalGraphQL unmarshals the provided GraphQL query data.
func (b *Long) UnmarshalGraphQL(input interface{}) error {
        var err error
        switch input := input.(type) {
        case string:
                value, err := strconv.ParseInt(input, 10, 64)
                *b = Long(value)
                return err
        case int32:
                *b = Long(input)
        case int64:
                *b = Long(input)
        default:
                err = fmt.Errorf("unexpected type %T for Long", input)
        }
        return err
}
```

A long literal in the query works ok, i.e. we can do `block(number: 1000000)`.
But passing it as a variable, i.e. `query test($num: Long!) { block(number: $num) }` and then `"variables": { "num": 1000000 }` fails with `"unexpected type float64 for Long"`.

**Comment by pavelnikolov** [comment]
@s1na  This does seem like a problem with your custom type rather than a problem with the GraphQL library. Have you tried adding `float64` to the list of possible types? For example:

```go
type Long int64

// UnmarshalGraphQL unmarshals the provided GraphQL query data.
func (b *Long) UnmarshalGraphQL(input interface{}) error {
        var err error
        switch input := input.(type) {
        case string:
                value, err := strconv.ParseInt(input, 10, 64)
                *b = Long(value)
                return err
        case int32:
                *b = Long(input)
        case int64:
                *b = Long(input)
        case float64:
                *b = Long(input)
        default:
                err = fmt.Errorf("unexpected type %T for Long", input)
        }
        return err
}
```

**Comment by pavelnikolov** [comment]
Let me know if the above fixes the problem. If you still have issues feel free to give me a failing unit test and I'll try to make it pass.

**Comment by holiman** [comment]
`block(number: 1000000)` is graphql, whereas `"variables": { "num": 1000000 }` is `json`. 
In the golang `json` library parser, an unquoted numeric literal is always parsed as `float64`. Hence the difference. I don't _think_ there's an issue with the `graphql-go` library.

**Comment by pavelnikolov** [comment]
I am closing this issue as I don't think that it is related directly to the GraphQL library. I don't think it is worth investing time in making JSON and GraphQL parsing the same.
