### ISSUE TITLE
Array of Input / Mutation

### ISSUE THREAD

**Issue by ibadaboom** [graph-gophers/graphql-go#526]
Hello,

I got a question. I tried since hours to achieve to following:

Let's assume, we got an Object called User. 

input User {
   id         int
   name   string
}

What I want to get is the possibility. to bind "User" to an array like [User] as an input and also have User available as Object,
Comming from node.js that was possible. 
But how this will work with your lib? Is this even possible? I Can only add 1 Input-Type of this name, resolving either as list or as object, but not both.

**Comment by pavelnikolov** [comment]
Can you, please, give me a sample query/schema? I am not sure I understand correctly what you want to achieve.

**Comment by ibadaboom** [comment]
Like this:
```
mutation saveUser has inputObject of type User returning Bool
saveUser(input: User): Boolean
and mutation saveUsers has inputObject of type []User returning Bool
saveUsers(input: [User]): Boolean
```

**Comment by ibadaboom** [comment]
I'm sorry, I found out, I posted into the false project. There are 2 project named the same.
