### ISSUE TITLE
Support `specifiedBy` directive

### ISSUE THREAD

**Issue by benzolium** [graph-gophers/graphql-go#531]
[`@specifiedBy` is in latest gql spec](https://spec.graphql.org/October2021/#sec--specifiedBy) so graphql-go should support it.

I'm using https://github.com/movio/bramble and recently encountered a bug when was trying to federate a service which contained `specifiedBy` directive. I've created an issue and [reply led me here](https://github.com/movio/bramble/issues/168#issuecomment-1232251447). 🙂

**Comment by pavelnikolov** [comment]
Thank you for reporting it. PRs are more than welcome.
