### ISSUE TITLE
Map must forcefully have type interface{}

### ISSUE THREAD

**Issue by MangioneAndrea** [graph-gophers/graphql-go#535]
Hello Graph Gophers

while working on an API, I noticed that the type Map could be implemented with a generic. (this requires go 1.18!)
I'll make an example:

let's say your field MyMap has type `map[string]string`.

currenlty you have to do 
```go
func (l Resolver) MyMap() types.Map {
	var result = make(types.Map)
	for key, v := range l.Entity.MapValue {
		result[key] = &v
	}
	return result
}
```

wouldn't it be prettier to do something like:

```go
func (l Resolver) MyMap() types.Map[string] {
       return l.Entity.MapValue.(types.Map[string])
}
```

The problem here would be compatibility with older versions, which might need some adjustments, maybe the next major version could support it?

Now, I'm ready to make the changes myself if there is no one against it

Cheers!

**Comment by pavelnikolov** [comment]
@MangioneAndrea thank you for posting this. Unfortunaetly, this would introduce a breaking change in the current version as you've mentioned. It will be considered for next major version, although, it's not planned for anytime soon. There is nothing stopping you from building your own custom scalar type which is a Map.
