### ISSUE TITLE
Supporting Json as a scalar type

### ISSUE THREAD

**Issue by sandeepatil1288** [graph-gophers/graphql-go#537]
Json would mean all the following options to be supported,

1. "String" -> String
2. {"Key": Value} -> map[string]interface
3. []String -> []interface

To represent this as scalar type we might need it to be interface{}
Since we cannot add methods to interface{}, it seems limitation on how we define a scalar type.

Please suggest way forward.

PS: I have checked [Issue-252](https://github.com/graph-gophers/graphql-go/issues/252), it only discusses about map version.

**Comment by pavelnikolov** [comment]
Could you, please, give an actual schema and a resolver?

**Comment by pavelnikolov** [comment]
Could you, please, give an actual schema and a resolver? I am going close this issue since it doesn't give enough details and it is not an issue with the library. Feel free to open another issue with an example schema and resolver describing your problem.
