### ISSUE TITLE
How to make it work in serverless application?

### ISSUE THREAD

**Issue by zhaoyi0113** [graph-gophers/graphql-go#549]
I am planning to build graphql serverless server in AWS lambda sitting behind API gateway. So it won't have any transport layer in the lambda. When it receives graphql request, it calls `schema.Exec` to execute the resolver. It works fine for query and mutation but doesn't work for subscription.

I got this error `graphql-ws protocol header is missing` when run `schema.Exec` on subscription request.  Based on this code: `https://github.com/graph-gophers/graphql-go/blob/5e160711131cf973a823ccef731a9b8c9e315005/graphql.go#L243`, it needs to call `schema. Subscribe ` method. My lambda doesn't have any transport dependency so it gets this error.

However, in order to call this method, I need to parse the graphql query string to find out whether call `schema.Exec` or `schema.Subscribe`. The parser in this library is from an internal package which is not open for public to call.

What is the best approach to achieve this.

**Comment by pavelnikolov** [comment]
Hi @zhaoyi0113,

I understand your problem but unfortunately we do not have a public method which parses the query and returns the operation name (e.g. `query`, `mutation` or `subscription`). Parsing the query should be pretty straightforward I guess. You just need to check if your query starts with `^\s*?subscription\s+?`. In that case call `schema.Subscribe`. Potentially we need to make some query parsing functionality public in this library but it is not in our immediate plans. At the moment, your fastest workaround would be to match the start of your query against a regex like the one above.

**Comment by zhaoyi0113** [comment]
Thanks for replying. I will use a library to do that parser like github.com/vektah/gqlparser/parser
