### ISSUE TITLE
What is the way to generate raw publish response?

### ISSUE THREAD

**Issue by zhaoyi0113** [graph-gophers/graphql-go#550]
I am building graphql server in AWS lambda + API websocket gateway. All resolvers and schema are loaded in a lambda. So there is no long running application.

I have a few questions about resolvers:

- In order to support subscription, I need to call `Schema.Subscribe` method to trigger the resolver. The resolver will save the connection ID and subscribed topic in a database in order for publish. When I look at Subscribe method signature:

```
func (s *Schema) Subscribe(ctx context.Context, queryString string, operationName string, variables map[string]interface{}) (<-chan interface{}, error) {
```

it returns a `channel` instance which requires the resolver to return a channel as well. It makes sense if I put the server in a long running application like a container. But in my case, the code is running inside a lambda and it will exit after resolver saves the connection information in the database. So what should I return in my resolver?

- When I receive a mutation request, I need to publish the data to all subscribers. What I am doing is to load all connection id based on the topic from database, then build a graphql publish response payload then post this payload to `AWS apigateway`. The problem I have is how to build the response payload. I couldn't find where it does that in this library. Any advice would be appreciated.

**Comment by pavelnikolov** [comment]
Hi @zhaoyi0113 
We have a reference naive implementation of a web socket transport https://github.com/graph-gophers/graphql-transport-ws. You can find a demo here: https://github.com/matiasanaya/go-graphql-subscription-example

You might build AWS Lambda transport for subscriptions. The library is agnostic to the transport you use.
