### ISSUE TITLE
Conditionally Disable Introspection

### ISSUE THREAD

**Issue by jcbwlkr** [graph-gophers/graphql-go#556]
First off, I love these libraries and they're my favorite way to build graphql servers in Go.

I have a need to enable introspection but for staff members only. Back in #309 when the option to disable introspection was added it was mentioned that gqlgen did this on a per-request basis (https://github.com/99designs/gqlgen/pull/447). I would love either a way to do that or a hook where I can somehow modify the request before it's done being parsed.

Currently the best solution I've come up with is to have two copies of the schema (one with introspection and one without) and use user roles to decide which schema to use inside my ServeHTTP

**Comment by pavelnikolov** [comment]
@jcbwlkr I agree with you that it would be nice to do that on a per-request basis. I believe we could offer a callback function where based on some context value the function returns true or false indicating whether introspection is allowed. We have to think how to introduce that in a backwards-compatible way. PRs are more than welcome.

**Comment by pavelnikolov** [comment]
I'm going to take a crack at this.

**Comment by pavelnikolov** [comment]
@jcbwlkr I implemented it in #569. Thank you, for raising this issue! I expect to release in `v1.6.0`

**Comment by jcbwlkr** [comment]
@pavelnikolov thanks so much! This looks great
