### ISSUE TITLE
Question on query string parsing

### ISSUE THREAD

**Issue by danny-xx** [graph-gophers/graphql-go#581]
The func for parsing query string is located under `/internal` package:
https://github.com/graph-gophers/graphql-go/blob/master/internal/query/query.go#L18-L28

Is there any concern for exposing this functionality to consumers? 

Here's my example use case for justification:
```
type Query {
    queryA: String!
    queryB: String!
    public: PublicQuery
}

type PublicQuery {
    queryC: String!
    queryD: String!
}
```

I want to skip authorization validation in middleware for any "public" queries. For example:
```
query getPublicQueryC {
    public {
        queryC
    }
}
```

In order to do this, I want to 
1. parse the query string in middleware 
2. check if the selections for this operation meets the "public" requirements
3. skip authorization validation middleware if that's the case

Is this the proper way for checking specific query groups? I would appreciate it if anyone has better ideas!

Thanks in advance!

**Comment by pavelnikolov** [comment]
Hi @danny-xx 
I would recommend declarative authorization whenever possible. Luckily, it is already possible to do this in the master branch. Check [this directive example](https://github.com/graph-gophers/graphql-go/tree/master/example/directives/authorization).
In addition to that in `v1.7.0` it will be possible to access the AST of the query and see all the fields and operations there.
