### ISSUE TITLE
More info on errors

### ISSUE THREAD

**Issue by EmperorEarth** [graph-gophers/graphql-go#60]
I've been using [Dave Cheney's errors pkg](https://github.com/pkg/errors) to add stack traces to all my errors. In dev, when I'm testing queries in graphiql/my app, I like to return the error directly in the response. I was wondering if there was any way to return the `%+v` version of errors back instead of the `%s` version, because right now, I'm not getting the line numbers of various errors and the rest of the stack trace.

**Comment by neelance** [comment]
See #49. I think the same solution should be possible in your case. If yes, then I should add some documentation to the readme since this question came up several times now.

**Comment by neelance** [comment]
Oops, I referenced the wrong issue in the commit. Reopening.

**Comment by neelance** [comment]
@EmperorEarth Any response to my comment above?

**Comment by tonyghita** [comment]
Not to hijack the issue, but the addition of query paths on errors to the specification seems near. See: https://github.com/facebook/graphql/pull/230

At first I was thinking of adding the `path` value after the query has executed and before we respond to the user, but I think this might be more appropriate in the library.

**Comment by EmperorEarth** [comment]
@neelance So sorry! I'll spend some time on this today and tomorrow.

I've been working on my startup prototype solo so long, I've gotten out of the habit of checking on Github/Slack.

**Comment by EmperorEarth** [comment]
@neelance, if I understand it right, it doesn't solve what I'm trying to do because the param is still `%s` in Printf, not `%+v`. But I don't really understand it at all, so?

As a basic example, as I'm rapidly writing code, sometimes I forget to check `err == sql.ErrNoRows()` before I check `err != nil` to return a `nil` resolver. With Cheney's `errors` package, if I wrap all my errors with the `func` `WithStack`, I'll get a line number.

I return all errors, and in my non-resolver code, only log them at the root. With graphql, however, we aggregate errors and proceed on the rest of the resolution as best we can. This is great, except when we return back to the client, in the client's `fetch().catch()`, `console.error(response.error)` gets an array of strings with very little contextual information. It gets very tedious to go through the response to see what did/didn't get returned. It would be helpful if the response to the client had the errors printed using `%+v` instead of `%s`, so the strings would have a line numbers.

Does that provide more context?

**Comment by EmperorEarth** [comment]
@neelance, if I understand it right, it doesn't solve what I'm trying to do because the param is still `%s` in Printf, not `%+v`. But I don't really understand it at all, so maybe it's better if I try to explain the yak I'm shaving?

As a basic example, as I'm rapidly writing code, sometimes I forget to check `err == sql.ErrNoRows()` before I check `err != nil` to return a `nil` resolver. With Cheney's `errors` package, if I wrap all my errors with the `func` `WithStack`, I'll get the full stack trace with line numbers.

I return all errors, and in my non-resolver code, I have an obvious endpoint to log the errors. I don't see that with your library. This is especially relevant because with graphql we aggregate errors and proceed on the rest of the resolution as best we can. What I have right now is an array of minimally helpful error strings sent back to the client as `%s`.

I guess what I need is threefold:
An understanding how to write a middleware layer just before the aggregated output is sent back to the server, giving me a chance to log my contextualized errors
A way to massage those errors at the end perhaps to not leak too many details back to the client, while still logging them all at my end
The flexibility to continue just returning errors at each of many resolvers, and choose a logging solution at a single place (probably makes sense to make it as late as possible before sending back to the client)

**Comment by neelance** [comment]
To me this still sounds like you need the same solution as #49. Take the list of errors returned by `Schema.Exec` and do with them whatever you want before encoding them as JSON and returning them to the client.

**Comment by MyOneTaps** [comment]
@tonyghita, we can close this now

`ResolverError` solves this, can't remember the PR #
