### ISSUE TITLE
query parser bug

### ISSUE THREAD

**Issue by Boyce-Lee** [graph-gophers/graphql-go#617]
query definition:
`OperationType Name_opt VariablesDefinition_opt Directivesopt SelectionSet`
detail in [gql spec](https://spec.graphql.org/draft/#OperationDefinition)
query parser logic is wrong: https://github.com/graph-gophers/graphql-go/blob/master/internal/query/query.go
```
func parseOperation(l *common.Lexer, opType ast.OperationType) *ast.OperationDefinition {
	op := &ast.OperationDefinition{Type: opType}
	op.Name.Loc = l.Location()
	if l.Peek() == scanner.Ident {
		op.Name = l.ConsumeIdentWithLoc()
	}
	op.Directives = common.ParseDirectives(l)  // wrong point => should ParseDirectives after ParseInputValue
	if l.Peek() == '(' {
		l.ConsumeToken('(')
		for l.Peek() != ')' {
			loc := l.Location()
			l.ConsumeToken('$')
			iv := common.ParseInputValue(l)
			iv.Loc = loc
			op.Vars = append(op.Vars, iv)
		}
		l.ConsumeToken(')')
	}
	op.Selections = parseSelectionSet(l)
	return op
}
```

**Comment by pavelnikolov** [comment]
Fixed in [this commit](https://github.com/graph-gophers/graphql-go/commit/12e9b901a628190cb35c85d315230a5fb7e6e584). Thank you for reporting this.
