### ISSUE TITLE
Issue with negative numbers

### ISSUE THREAD

**Issue by otboss** [graph-gophers/graphql-go#624]
With the   **graph-gophers/graphql-go** package there seems to be an issue with negative number support. See the error message in the image attached:

![image](https://github.com/graph-gophers/graphql-go/assets/24215073/9db73da3-b32d-416f-814f-f88fb8c06231)

As shown, sending a negative float number to a resolver result in an error message being returned.

**Comment by otboss** [comment]
This issue appears to be fixed in a later version.

**Comment by otboss** [comment]
I propose the following fix as to not dismiss the minimal boundary entirely:
![image](https://github.com/graph-gophers/graphql-go/assets/24215073/0eba6e6f-eb19-41cf-8080-4baf54f3a93f)

**Comment by pavelnikolov** [comment]
Actually, I don't think we need to check the boundary at all since `strcov.ParseFloat(v, 64)` would return an error if that isn't a valid float64 number. No need to check for boundaries. If you still believe there are some problem, please send a failing unit test. Thanks.
