### ISSUE TITLE
Please add simple example without react, relay, http etc... 

### ISSUE THREAD

**Issue by mvestnik** [graph-gophers/graphql-go#629]
Why do all the examples use a third-party optional library or http server? 
In github.com/graphql-go/graphql complex declarative synthax, but it's easier to understand than your "simple and idiomatic" one.

**Comment by mvestnik** [comment]
Alternative variant - add example in schema.Exec() documentation

**Comment by pavelnikolov** [comment]
When you run the examples locally using the godoc tool you can see plenty of examples. However, your feedback is highly appreciated and I'd be happy to improve any examples that look confusing or complicated.

**Comment by pavelnikolov** [comment]
PS, a 1.6 release is coming out soon.
