### ISSUE TITLE
OverlappingFieldsCanBeMerged raises no error when an error should be raised

### ISSUE THREAD

**Issue by ssko1** [graph-gophers/graphql-go#647]
### Test Case

```go
func TestUnionFragmentOverlappingFields(t *testing.T) {
	sdl := `
	type Foo {
      s: Int
    }

    type Bar {
      s: Int!
    }

    union FooBar = Foo | Bar

    
    type Query {
      foobar: FooBar
    }
`

	q := `
	fragment A on Foo {
		s
	}

	fragment B on Bar {
		s
	}

	query { 
		foobar {
			...on Foo {
				...A
			}
			...on Bar {
				...B
			}
		}
	}
`

	s := graphql.MustParseSchema(sdl, nil)

	errs := s.Validate(q)
	if len(errs) == 0 {
		t.Fatal("expected overlapping fields error")
	}
}
```

### Explanation
The test case above should produce an error because `Foo.s` of type `Int` cannot be merged with `Bar.s` of type `Int!`.

### Hints and Other Notes
The following query produces an error as expected, which hints at a defect in how `validateOverlap` considers fragments inside inline fragments.
```graphql
	query { 
		foobar {
			...on Foo {
				s
			}
			...on Bar {
				s
			}
		}
	}
```

**Comment by pavelnikolov** [comment]
Hi @ssko1,

Thank you for dedicating time and posting this issue. I did review your test case carefully and it seems that this is actually the expected behavior. Unlike interfaces, [unions](https://spec.graphql.org/October2021/#sec-Unions) give no guarantees of the underlying types and their fields:
> GraphQL Unions represent an object that could be one of a list of GraphQL Object types, but provides for no guaranteed fields between those types. They also differ from interfaces in that Object types declare what interfaces they implement, but are not aware of what unions contain them.

Given the above I am going to close this issue. Feel free to comment/re-open it if you think that there is actually an issue.

**Comment by ssko1** [comment]
@pavelnikolov thanks for looking into this. 

Interestingly, a simpler variation of this test case that I created against the javascript and java implementations _pass_ the test.

Here's the javascript test, for example:

```javascript
  it('union fields overlapping fields', () => {
    const schema = buildSchema(`
        type Query {
          foo: MyUnion
        }
        
        union MyUnion = StringRequired | StringOptional
        
        type StringRequired {
          field: String!
        }
        
        type StringOptional {
          field: String
        }
    `);

    expectValidationErrorsWithSchema(schema, OverlappingFieldsCanBeMergedRule,`
      {
            foo {
              ...on StringRequired {
                field
              }
              ...on StringOptional {
                field
              }
            }
        }
    `)
  })
```

I'd love to hear your thoughts on this, there seems to be an inconsistency in how reference impls handle this use case.
